### ISSUE TITLE
[V3 Audio] YouTube Search listing the first X Items to play

### ISSUE THREAD

**Issue by TheLux83** [Cog-Creators/Red-DiscordBot#1000]
Hey there,

Before using RedBot, we used FredBoat. When you search for a song on Youtube via FredBoat, it lists the first 5 results, when it isn't able to specify your song request directly (Like Frog Leap Studio vs Frog Leap Studio Africa).
When you search via RedBot it seems it doesn't matter if I search via [p]play or [p]yt.

My Suggestion is, that if you search via [p]yt that i will list the first X Results and you can choose which song you wanted to play.

This is my first suggestion. I hope I did everything right. If not, please correct me :)

**Comment by fididev** [comment]
I'd suggest also to make it that to select a result from the search you'll use reactions instead of manually typing the number.

Like [this](https://camo.githubusercontent.com/7218aef3a15d71bdd84c04051fb6f28b61115377/68747470733a2f2f692e696d6775722e636f6d2f74657672744b742e706e67).
Pic taken from [jagrosh's MusicBot](https://github.com/jagrosh/MusicBot) (in case you want to take a look at the source code aswell).

**Comment by Tobotimus** [comment]
Good suggestions, could be implemented in V3 audio eventually, however we won't make plans for it until Audio is actually rewritten for V3.

**Comment by tekulvw** [comment]
Should be implemented in B10
