### ISSUE TITLE
Config vars

### ISSUE THREAD

**Issue by Sleedyak** [Cog-Creators/Red-DiscordBot#1004]
What are the red config vars?  I really wanna host it on Heroku..

**Comment by palmtree5** [comment]
>**Take advice at your own risk. Red isn't built for Heroku. This is due to the fact that our data structure isn't setup for it, and it won't be for a long time. It's a security risk by not commiting the token data to a env var.**
One Heroku user (jamfarts) wrote:  I had to set it all up first locally so that I HAD the settings TO commit. Then I had to commit the settings. I cloned the repo and committed to my own, with the /data folder and all its contents. I can't rely on it for anything time related overnight. Any changes I need to do I have to pull it down, do them locally, commit it, and restart the bot. So if I want to add to the filter list, or custom commands, I have to do that.

**Comment by Kowlin** [comment]
Looking back at the commit history of v2, there is actually an option to use a [env var](https://github.com/Cog-Creators/Red-DiscordBot/pull/513/commits/3ff102467a6b5a75098e4c448a604d831276a02e) for Red. By setting the var ``RED_TOKEN`` to a valid token the bot will log in via env var. This will take priority over the config. Hope this helps a bit.
