### ISSUE TITLE
[Suggestion] Make the filter log in mod log or in audit log

### ISSUE THREAD

**Issue by ncodex2** [Cog-Creators/Red-DiscordBot#1011]
When the bot deletes a message, it doesn't log anything to mod log or in audit log, making it impossible to ban the user that consecutively enters the filtered message.

**Comment by MiniJennJenn** [comment]
1. Does it matter if they continuously enter the message if it gets deleted immediately kek
2. It's a possible suggestion to consider for v3. However, in the meantime, you should look into the grenzpolizei cog by Paddo which logs pretty much everything. (Feel free to read about it in the #spotlight channel in the discord server).

**Comment by palmtree5** [comment]
The audit log part of this isn't happening because the library doesn't support adding an audit log reason for a message delete. As for the suggestion of the mod log case, I'd rather go the route of having an option in (that would probably be disabled by default) that would autoban if the user had some configurable number of filtered messages in a configurable amount of time

**Comment by Kowlin** [comment]
It was actually told by a Discord staff member that they will not support adding message deletion if its done by bots since: "Bots will delete so many messages that it spams the system".

**Comment by palmtree5** [comment]
The autoban (with a modlog case) is in 3.0.0b1 and is disabled by default.
