### ISSUE TITLE
No discord.py 

### ISSUE THREAD

**Issue by fallenfrost** [Cog-Creators/Red-DiscordBot#1190]
I looked everywhere in my bot folder and couldnt find it anywhere. I dunno if its somewhere else or if it just didnt download in the bot folder. its probably somewhere and im just dumb and cant find it hahah

**Comment by Zephyrkul** [comment]
Please ensure you have followed all steps in the installation guide for your OS. You can find installation guides in the docs: https://twentysix26.github.io/Red-Docs/

For further questions, it's recommended to join the Discord support server: https://discord.gg/red

**Comment by Tobotimus** [comment]
To add to what Zephyr said, we require a bit more detail about issues, e.g. what the actual problem is, and steps to reproduce. Regardless, this sounds like more of a support question than an issue with the bot.

I'm closing this for now, if you have more detail about the issue, you can comment here, and it may be re-opened.
