### ISSUE TITLE
[V3 Suggestion] Just suggestions

### ISSUE THREAD

**Issue by IdkGoodName** [Cog-Creators/Red-DiscordBot#1210]
### Suggestions for v3 
>Staff Suggestion 

I think you should add like moderator and co owner 
Moderator wouldn't able to manage cogs and etc, but if economy is global, he could give himself and others credits, also other small non harmful commands...
Co-owner is basically like --co-owner flag in v2, but you could have multiple of them like mods... 
Also you should be able to add them with commands :/...  

>[p]dm2 

[p]dm2 would be like dm command, but it would be little bit diffrent: 
Instead of this msg: 

> ## Owner of BotName#BotDiscriminator 
> ## Hi
> You can reply to this message with ==contact 

you would get: 
Hi 

I like current dm, but i will probably need regular dm msg... 

>Editable Help 

I think in **RED V3**, you should be able to edit help... 
What i mean by edit help, is that you should be able to send cogs to categories 
For example: 
i want `[p]twitch` to be in general category and it is now in general category.

You could also hide stuff for example: 
I want to hide command `[p]8` and now regular people can't see it, only me, co-owners and mods... 

I bet you won't read it or won't add suggestion label probably...

**Comment by Tobotimus** [comment]
>I think you should add like moderator and co owner
Moderator wouldn't able to manage cogs and etc, but if economy is global, he could give himself and others credits, also other small non harmful commands...
Co-owner is basically like --co-owner flag in v2, but you could have multiple of them like mods...
Also you should be able to add them with commands :/...

>You could also hide stuff for example:
I want to hide command [p]8 and now regular people can't see it, only me, co-owners and mods...

These features will be available in the Permissions cog, which is essentially rewrite of permissions from Squid-Plugins.

>[p]dm2 would be like dm command, but it would be little bit diffrent:
Instead of this msg:
Owner of BotName#BotDiscriminator
Hi
You can reply to this message with ==contact
you would get:
Hi

I don't know exactly what you're suggesting here, but there's no need for this to be core, it could easily be part of a 3rd party cog.

>I think in RED V3, you should be able to edit help...
What i mean by edit help, is that you should be able to send cogs to categories
For example:
i want [p]twitch to be in general category and it is now in general category.

This isn't going to happen since commands are categorised based on which cog they come from - the category is literally the name of the cog. Changing this at runtime wouldn't make any sense.


All in all, suggestions need more justification before we will consider them for core. These suggestions just seem to be made for the sake of it. If you have more justification to back up your suggestions, please comment them here.

**Comment by Tobotimus** [comment]
Closing due to staleness
