### ISSUE TITLE
[V3 Launcher] Redbot fails to boot if the username of the bot account has special characters

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#1366]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
When you have "special" characters in your bot's username, the launcher fails to boot redbot.

### Expected behavior
The launcher boots redbot normally. When it cannot print certain characters in the bot's username in the launcher, it prints a last-resort character (like "?") instead.

### Actual behavior
This error is printed, and the launcher never boots the bot:
```
File "D:\Applications\Python35\lib\site-packages\discord\client.py", line 223, in _run_event
    yield from coro(*args, **kwargs)
  File "D:\Applications\Python35\lib\site-packages\redbot\core\events.py", line 143, in on_ready
    print(bordered(INFO, INFO2, ascii_border=ascii_border))
  File "D:\Applications\Python35\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "D:\Applications\Python35\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "D:\Applications\Python35\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "D:\Applications\Python35\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "D:\Applications\Python35\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xb3' in position 77: character maps to <undefined> 
```

### Steps to reproduce

1. Create a bot account, and name it something with a special character in it (like "TestBot³")
2. Install the bot
3. Log in with the token of that bot account
4. Error appears, as the launcher cannot print that character.

**Comment by Tobotimus** [comment]
I believe this issue is mostly specific to (legacy) command prompts which use code pages (CP). The typical culprit is Windows Command Prompt. Also, Python 3.6 and above doesn't seem to have this problem as it replaces characters not in the active code page, just as you suggest in the Expected Behaviour.

Moreover, this issue is a real pain to solve. There's no way we can anticipate characters not in the CP being printed to the console, moreover there isn't really a pythonic/efficient way of replacing said characters before printing them.

There are a bunch of workarounds available to you though:
 1. If you're using windows command prompt, do `chcp 65001`
 2. Use PowerShell or any other command prompt which doesn't have this issue
 3. Upgrade to python 3.6

I'm leaving this open for now but I don't think we're going to see a proper fix for this implemented, I'm sorry.

**Comment by Tobotimus** [comment]
Setting this as wontfix and closing. If anyone stumbles across this issue looking for a solution, please see the workarounds above.
