### ISSUE TITLE
Multiple bots in one server

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#1442]
I currently have the Red bot setup for my server. However, I have 3 different music channels. How would I add 2 more Red bots to my server?
If I host 3 bots on my computer, is there a way for them to sync playlists between them?

**Comment by calebj** [comment]
> I currently have the Red bot setup for my server. However, I have 3 different music channels. How would I add 2 more Red bots to my server?

Set up two new instances of Red in two new folders. Treat them as separate bots, because they are. That means create an app on the Discord developer page and go through the setup process for them just like your first one.

> If I host 3 bots on my computer, is there a way for them to sync playlists between them?

After reading over the code, it looks like this is possible, since playlists aren't loaded into memory before they're requested or modified. Symlink the `audio/localtracks` and `audio/playlists` folders in all but one of the bots to the remaining real copy. Both Windows, Linux and OSX can do this; google the appropriate steps for whatever OS you're on.

**Comment by ghost** [comment]
Worked perfectly! I can add/remove playlists on one and it will sync the rest. Thanks!
