### ISSUE TITLE
No !yt command

### ISSUE THREAD

**Issue by KrizKhaoz** [Cog-Creators/Red-DiscordBot#1627]
I've looked on the page and noticed it states there is a !yt command as well as a !play command but there is no command at all that supports that...

**Comment by pgaetani** [comment]
[p]yt was available in v2, if you're using v3, it's all handled through [p]play

**Comment by Kowlin** [comment]
If I recall correctly while not looking at the code ``yt`` is alliased to ``play`` and non existent on V3 since its build into play. If you don't have the ``play`` command that means ``Audio`` is unloaded and you can check by using the ``cogs`` command, and you can load ``Audio`` by using the ``load`` command.

For faster support please [visit our Discord server](https://discord.gg/red) (the preferred way) instead.
