### ISSUE TITLE
[Economy] Using [p]leaderboard in DM causes an error

### ISSUE THREAD

**Issue by Hendersonyt** [Cog-Creators/Red-DiscordBot#1637]
# Command bugs

#### Command name

(prefix)leaderboard

#### What cog is this command from?

Economy

#### What were you expecting to happen?

Display the global leaderboard, or display a message stating that the command isn't available in DMs.

#### What actually happened?

https://drive.google.com/file/d/1-9V_y2KJ9oCJQLUpmvY6kvd1LBG5b39Q/view?usp=drivesdk

#### How can we reproduce this issue?

I found out that I did it in a DM and not in a server. I got it working on my server, however, should
say something like: "That command is not available in DMs." and she did not say that.

**Comment by Redjumpman** [comment]
It looks like the link to your screenshot is broken. Can you update your issue with a new link?

**Comment by Hendersonyt** [comment]
Fixed, someone needs to stop changing the link.

**Comment by palmtree5** [comment]
I'm unable to reproduce that error as I'm getting the intended behavior when doing the command in a DM (i.e. getting the leaderboard if the bank is global, or a message stating that I can't run the command if it's not)

**Comment by Hendersonyt** [comment]
That is weird.

**Comment by palmtree5** [comment]
Can you screenshot the output of `[p]info`? I suspect you might be on an older version after rereading the traceback in the screenshot you provided

**Comment by palmtree5** [comment]
Actually, another reread leads me to believe you're on V2, not V3

**Comment by Hendersonyt** [comment]
How? I keep shoving the update command.

**Comment by palmtree5** [comment]
you can't update from V2 to V3 the way you would update V2 itself because V3 is a massive breaking change compared to V2. Cogs written for V2 won't work on V3 without being rewritten to work with V3.

If you're interested in getting started with V3, see https://red-discordbot.readthedocs.io/en/v3-develop/ (note that you will probably want to use a virtualenv if you want to try V3 while also continuing to use V2 because they use different versions of discord.py).

All that being said, you definitely did find a bug in V2's economy cog, so I will leave this open

**Comment by Hendersonyt** [comment]
I shoud upgrade to the latest version if you guys stop support v2. I don't have money to get a VPS. Yes this is a bug in version 2, and you can keep it open if you want.

**Comment by palmtree5** [comment]
Oh, I didn't mean a VPS, I meant something like https://virtualenv.pypa.io/en/stable/ or https://docs.python.org/3/library/venv.html

**Comment by Hendersonyt** [comment]
Oh, or vitural box.
