### ISSUE TITLE
[V3 Config] Reload JSON files

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1651]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

Previously, on V2, when I was reloading a cog with dataIO, it was also reloading all of the json files. Now that we use Config, I'm still used of directly editing the `settings.json` files for testing (yeah ik, edit red is bad, but I'm a cog creator so no). 

The problem is that when I reload my cog, the `settings.json` file is **not** reloaded too. I need to restart the bot to get the changes. Maybe you should modify config so it reload settings files on a cog reload.

**Comment by tekulvw** [comment]
What happens if you `!unload` and `!load` again?

**Comment by laggron42** [comment]
It's the same

```Py

El Laggron - Today at 1:18 PM
!debug __import__('os').remove('Red/cogs/InstantCommands/settings.json')

RedBOT - Today at 1:18 PM
None

El Laggron - Today at 1:19 PM
!debug __import__('os').listdir('Red/cogs/InstantCommands/')

RedBOT - Today at 1:19 PM
[]

El Laggron - Today at 1:19 PM
nice
!reload instantcmd

RedBOT - Today at 1:19 PM
Package instantcmd was reloaded.

El Laggron - Today at 1:19 PM
!instacmd info

RedBOT - Today at 1:19 PM
Error in command 'instantcmd info'. Check your console or logs for details.
# existing problem in the loaded json

El Laggron - Today at 1:19 PM
!unload instantcmd

RedBOT - Today at 1:19 PM
Package instantcmd was unloaded.

El Laggron - Today at 1:19 PM
!load instantcmd

RedBOT - Today at 1:19 PM
Loaded instantcmd

El Laggron - Today at 1:19 PM
!instantcmd info

RedBOT - Today at 1:19 PM
Error in command 'instantcmd info'. Check your console or logs for details.
# still the same problem

El Laggron - Today at 1:20 PM
!restart

RedBOT - Today at 1:20 PM
Restarting...

El Laggron - Today at 1:20 PM
!instantcmd info

RedBOT - Today at 1:20 PM
No instant command created.
# successfully reloaded
```

**Comment by mikeshardmind** [comment]
Don't mess with those files manually, because of the way data is loaded you would need to unload, delete, and then load. instead use a better debug statement (or better, eval) to interact with config.

```py
[p]eval await bot.get_cog('SomeCog').some_config.clear_all()
```
or
```py
[p]eval
from redbot.core.config import Config

x = Config.get_conf(None, 42, True, cog_name='SomeCog') # Make sure to use the right identifier
await x.clear_all()
```

**Comment by laggron42** [comment]
That was just an example, the problem is: Config doesn't reload JSON files on reload.

And editing the JSON instead of getting the object is so much faster and easier when testing cogs. I was used of this on v2, and I think we could implement file reload when a package reload is done.

**Comment by mikeshardmind** [comment]
Config was not designed for this, and should not need to account for this. It was designed to store data without the cog creator ever directly interacting with whatever the bot owner set as a storage back-end. Modifying those files manually may have unexpected results if you don't understand how Config is handling them. This is not a flaw with Config.

**Comment by Tobotimus** [comment]
It's not a flaw with Config, and @retke isn't making it out as one - it's a feature request.

*Perhaps* we could look into refreshing the driver cache within `Config.get_conf`. I have a suspicion these issues could be resolved by a better design/ less misuse from the cog creator, but at the same time I understand that data coherency is a desirable feature. I'll look into it if I get the chance.

**Comment by mikeshardmind** [comment]
Maybe I should clarify. A tool *can't* be responsible for what happens when you intentionally bypass the sole purpose of the tool. And that a tool shouldn't include functionality specifically because someone doesn't want to use it. There are plenty of ways to modify data in Config safely, but manually modifying files which Config owns, while it is using them is not a case we should have to plan for, when the explicit purpose of Config was to not have Cog creators touching data stores manually to begin with.

**Comment by tekulvw** [comment]
First off, I'd like to state that Config *does* reload JSON data from disk when reloaded. Once config detects that all driver objects referencing a particular cog's data have been garbage collected it dumps the JSON cache and on next load will load that data from disk. However, because of a lot of technical reasons, it is *possible* that the new cog object is instantiated before the old one can be garbage collected. This is a race condition and unintentional but likely unavoidable consequence. Simply using `!unload` and waiting a second or two before using `!load` again should give you the behavior you want.

With that being said, this is not truly a bug because you are directly modifying files that should be entirely controlled by config and the config driver. As has been said above, use config functions where possible and for the future we may be able to add file change detection for the JSON driver, although that is not near the top of our current priorities. If you use Mongo you will never experience this issue and, in fact, will not even need to reload.

**Comment by laggron42** [comment]
okay thanks
