### ISSUE TITLE
[V2 General] Urban command returns "Error."

### ISSUE THREAD

**Issue by viggou** [Cog-Creators/Red-DiscordBot#1677]
# Command bugs

#### Command name

!urban

#### What cog is this command from?

general.py

#### What were you expecting to happen?

I was expecting the bot to return a definition of a word

#### What actually happened?

The bot returned "Error."

#### How can we reproduce this issue?

1. type !urban <word>
2. done
![2018-05-18_14-14-42](https://user-images.githubusercontent.com/14791119/40246351-b6c90126-5ac8-11e8-89e5-250f69081c90.png)

**Comment by Redjumpman** [comment]
Can you show a screenshot of the error message you received in your console?

**Comment by viggou** [comment]
It doesn't say anything...

**Comment by viggou** [comment]
![2018-05-24_18-59-49](https://user-images.githubusercontent.com/14791119/40500345-b8c3612c-5f84-11e8-87ef-9281db943f71.gif)

**Comment by tekulvw** [comment]
Gonna have to say "wont fix" to this for V2.

**Comment by skeith** [comment]
I know an error on urban that caused by recent aiohttp version because v2 urban uses a deprecated function. If your aiohttp version is higher than or equal 2.3.2, there is a fix already PR'd (#1116)

@viggou can you run this command on discord and tell me the output
`!debug  __import__('pkg_resources').get_distribution("aiohttp").version`
