### ISSUE TITLE
[V3 Permissions]

### ISSUE THREAD

**Issue by Ray-MRQ** [Cog-Creators/Red-DiscordBot#1735]
# Command bugs

#### Command name

p addglobalrule

#### What cog is this command from?

Permissions

#### What were you expecting to happen?

To deny global commands

#### What actually happened?

Since it's a _global_ rule, why would it require a "what" or a who". This is the following command that I had run.
![image](https://user-images.githubusercontent.com/10146271/40610630-17e316aa-626b-11e8-8e71-a314fc4aa330.png)
![image](https://user-images.githubusercontent.com/10146271/40610684-5516e722-626b-11e8-82ee-14f6c9059c0f.png)

#### How can we reproduce this issue?

Attempt a addglobalrule

**Comment by flaree** [comment]
It uses IDs, enable developer mode and right click the server icon and Copy ID.

![discord_2018-05-28_12-27-01](https://user-images.githubusercontent.com/31554168/40612444-703ad336-6272-11e8-83fb-1fabdf5a034c.png)

**Comment by mikeshardmind** [comment]
Copy-pasting my response from #v3-support in case anyone else comes across this as an issue.

You probably want `[p]permissions setdefaultglobalrule contact deny` The permissions doc here <https://red-discordbot.readthedocs.io/en/v3-develop/cog_permissions.html> has a bit more info on all that, and I'll also be adding some example configurations to the docs later.

Naming issue on the command you pointed out was due to differing definitions for 'global' (I was using it to refer to where the rule applied, and it may have made more sense to name it "ownerrules")

**Comment by tekulvw** [comment]
Misunderstanding of command, closing. Feel free to comment again or come to #v3-support if there are further questions.
