### ISSUE TITLE
[V3] Standardized command/subcommand name for generic command types

### ISSUE THREAD

**Issue by skeith** [Cog-Creators/Red-DiscordBot#1749]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

For generic command such as add/create, del/delete/remove, it's better to be standardized to use the same standard for at least core cogs. Take a look at this image below

![image](https://user-images.githubusercontent.com/340284/40746555-57d8cb78-648d-11e8-9d71-8eb54e7c0e65.png)

As seen above, CC uses delete, while ALIAS uses del
This create issue of consistency and I sometimes failed on remembering which one use del/delete

I'd also hope for the future 3rd party cog approval method (beta/approved) this standard also enforced

**Comment by skeith** [comment]
Since audio uses both delete and remove and it's both valid for the description its having. I think if this standard to be passed, something must be agreed first on what kind of commands we force the standard and what if more than one of the similar generic command exist 

![image](https://user-images.githubusercontent.com/340284/40747618-6a09e752-6490-11e8-9a50-f45a138dc9c5.png)

**Comment by Tobotimus** [comment]
Thanks for  bringing this forward - and I agree, consistency is important, especially across different core cogs.

I'm pinning this to Beta 17 because I don't want the decision made on this to be rushed, but we could see this sneak its way into Beta 16.

As for my opinion on this standard, I think audio gets it right - `delete` is for deleting the object referred to by the supercommand (in this case the "playlist") whereas `remove` should refer to removing something *from* the object. I also think that in any case for a command named `delete` it should have an *alias* `del`.

The same can be said about `create` and `add` - `create` is for creating a new object, `add` (or `append` in the playlist's case) is for adding something *to* the object. Although I personally wouldn't mind if something like `[p]cc add` became `[p]cc (create|add)`, since it's an established command, and there isn't really another use for the `add` subcommand in this case. 

CC: @palmtree5 @tekulvw

**Comment by skeith** [comment]
I understand that `add` and `create` might be used both at the same time, but for cogs that has no `add` and `create` I think it's better to be standardized. A standard like priority of words to be used, such as : add -> create, which mean you have to use `add` first, unless the description/function is not suitable.

To be honest, my main issue is with `delete` and `del`. Since this one is the same. I am suggesting to list `delete` as main command with `del` as alias
