### ISSUE TITLE
[V3 Help] Remove help from help list

### ISSUE THREAD

**Issue by Eslyium** [Cog-Creators/Red-DiscordBot#1759]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature
Its a basic thing that most users should know the command and already know what it does. The
No Category/help command in the help command should be removed If possible or reworded to state you can do help cog name.

**Comment by mikeshardmind** [comment]
Removing this to add that that info in there, could conflict with changes introduced in #1705 which is intended to allow customization of that section, and leave users without that info. I think it may be more appropriate to modify help to instead be hidden so that it's available if used as `[p]help help` but not taking up additional space.

Edit: I'm being an idiot, this is the only way to remove it from the list in the current help formatter anyway without removing the command.

**Comment by Tobotimus** [comment]
I agree we don't really need the help command to be shown - it'd be fine by me if it only took up one line, but having its own category it takes up more space than deserved, and that's not something I want to manually tweak. 

Simply making the command `hidden` is fine by me.

**Comment by tekulvw** [comment]
Having help be `hidden` sounds good to me.

**Comment by palmtree5** [comment]
Done in #1772
