### ISSUE TITLE
[V3 Mod] Make mute server use a role

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1852]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

The `[p]mute server` edit every channel permissions. This requires a lot of API calls and is really slow to operate (it takes about 6 seconds for 10 channels, so imagine on huge servers) and we could reduce that time by muting using a role instead of editing the channel permissions. 

This should be optional so users can decide what they want between a fast server mute with a role or a slow mute with channel perms.

**Comment by Tobotimus** [comment]
This is a well presented suggestion, it has a few issues though. I agree that the current `[p]mute server` command is too API spammy. However applying a role instead is a change in behaviour, so this could be a separate command (*cough punish cough*). One use of `[p]mute server` is to quickly restrict a user to a small number of channels by doing `[p]mute server` followed by `[p]unmute channel`, because doing `[p]mute channel` in every other channel would take a long time. Applying a muted role to a person changes the behaviour in that `[p]unmute channel` wouldn't do anything to someone who is server-muted.

An alternate approach might be to allow roles to be muted the same way users can, then mods can just apply a muted role. This avoids changing the behaviour of `[p]mute` but doesn't solve the API spammy nature of the command itself. I'm open to more discussion :)

**Comment by laggron42** [comment]
Maybe we could still use a role for guild mute and, when using channel unmute, force the `send_messages` permissions in the channel (ignore role perms)? But another issue would be to remove that forced permission, but when... 

I already started working on that feature, you can check the `mute` branch of my fork (the work currently done ignores what you suggested, but I will look after it). 

Another addition not specified in the issue is that, when using `mute` without subcommands, it will be default to a guild mute (my moderators were lost because they were just trying to `[p]mute @someone`)

**Comment by calebj** [comment]
I had an idea for solving this problem in v2 punish that I'll try to implement and test today. Will comment with how it goes.

**Comment by mikeshardmind** [comment]
This *cannot* be reliably done with a role without a server's permissions being designed for this usage. 

If this makes it into core, it needs to error in cases it would be ineffective with a clear reason why presented to the user.

Discord's developer docs on permissions explain this, but not really in good user-facing terms. If a user has any role allowing something (other than the default role), any role-based denies won't matter since non-default role allows are batch applied *after* batch applying non-default role denies.

This ends up making it so that channels which are invisible to most, visible but mute to role B and non-mute to role C can't be effectively muted without also revoking read permissions without assigning permissions granularly, and ensuring members of C are also members of B. 

It gets significantly more convoluted with more restricted channels. 

I'm of the opinion it's worth supporting, but given the various caveats for it, it needs to be opt-in, with well-documented reasons as to why, and how to properly configure it, and warn users if it isn't going to work on someone they attempt to mute with it.

**Comment by mikeshardmind** [comment]
replaced by #3270
