### ISSUE TITLE
Streams needing to be reloaded regularly

### ISSUE THREAD

**Issue by Sashasonic** [Cog-Creators/Red-DiscordBot#1940]
I've found that the Streams Cog is needing to be reloaded quite a bit (it'll just stop issuing Twitch Alerts) Once reloaded, it'll post a bunch of them at once. 

Is this a known issue, or could it be triggered by something (like a member going on and offline a lot?) 

Thanks,

**Comment by Tobotimus** [comment]
@Sashasonic sorry for the slow response, but thanks for bringing the issue forward to us.

This can just be the twitch API being slow. I've noticed in the past that according to the twitch API, a user can be streaming in excess of 10 minutes after they've gone offline. If a member comes back online within this time, the bot can assume it's already posted an alert for that channel since it never detected the channel going offline, so yes indeed a member going on and offline a lot can cause this behaviour. Is this the only time this issue is occurring for you?

Edit: I should clarify. Is this for V3 or V2?

**Comment by Sashasonic** [comment]
Hi @Tobotimus That's ok, better late than never, tbh I haven't been monitoring the situation in a while (as I have 3 different bots that post 'alerts') _but it had been occurring quite a bit_. There was a member that was experiencing on/offline status, and thought it may have been part of causing the issue. Albeit, I'll continue to monitor the situation again.

Yes it's v2 (my _dev_ v3 is also snagged with needing to add and remove repos - so I leave it alone, didn't know it did stream alerts - or maybe I forgot; waiting till it's over the bug)

Thanks for the information,
Sasha

**Comment by Tobotimus** [comment]
Since it's V2, nothing's changed in the streams cog for a very long time, and no one else seems to be reporting the issue. I'm gonna put this down to the twitch API being a little slow.
