### ISSUE TITLE
Disable globally, enable per channel

### ISSUE THREAD

**Issue by chnaski** [Cog-Creators/Red-DiscordBot#1946]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature
I think it should be an option to disable things globally but then enable them per channel, so it'd be ``[p]set deletedelay 0`` but then ``[p]set deletedelay -1 #somechannel``

**Comment by Tobotimus** [comment]
Thanks for your suggestion. I agree this would greatly enhance the UX. We'll try to keep this suggestion in mind going forward, but implementing it in existing features (such as your example suggestion) will take some time. Freezing for now until our schedule frees up.

**Comment by Flame442** [comment]
Adding extended configuration option in different scopes can balloon in complexity quite quickly, especially with how many different settings there are in core (see the permissions cog). While I know that this sort of thing is often requested (more often with things like global defaults for the audio cog, rather than having to manually apply the same setting in multiple servers), I don't think it's something we can prioritize doing in bulk. Since this is a very old issue, I'm going to close it, but if anyone reading this would like to suggest adding configuration to different scopes for more *specific* cases, those can still be handled individually.
