### ISSUE TITLE
[V3 Cleanup] "Cleanup After" command is unresponsive

### ISSUE THREAD

**Issue by Crossedfall** [Cog-Creators/Red-DiscordBot#1947]
# Command bugs

#### Command name

`[p]cleanup after`

#### What cog is this command from?

Cleanup

#### What were you expecting to happen?

When running the command with a valid message's ID _(in this case 469161892099653652),_ it should remove any messages allowed by Discord's API following said message.

#### What actually happened?

Nothing. No errors are provided and no messages are deleted. Debug log below:

> Jul 18 11:30:26 red python3[3398]: [18/07/2018 11:30] INFO cleanup after 254: Crossedfall([removed]) deleted 0 messages in channel crosssed-bots.

#### How can we reproduce this issue?

Attempt to delete messages using the command `[p]cleanup after <message-ID>`

#### Bot Info
![image](https://user-images.githubusercontent.com/26130695/42891683-90d66d14-8a75-11e8-8c7f-7256177b489b.png)

**Comment by laggron42** [comment]
I have that problem too

**Comment by Brramble** [comment]
Can confirm I am also having this issue.

**Comment by mikeshardmind** [comment]
There seems to be an issue with the after parameter in general when requesting channel history from the API. I'm not sure what can be done to remedy this, but I will look into it more closely later. 

Edit: This also appears to be inconsistent in when it is an issue.

Edit 2: There's an additional logic flaw to be accounted for here, we're short-circuiting out of the collection due to an issue with ordering of messages.

**Comment by Tobotimus** [comment]
Hotfix #2004 resolves this. #1980 is a more general solution which will be merged at a later date.
