### ISSUE TITLE
Moderation modlog feature

### ISSUE THREAD

**Issue by safaci2000** [Cog-Creators/Red-DiscordBot#2135]
# Feature request

I would love the ability to permission users for moderation by role rather then listing users individually.

Also, the ability to modlog a deleted message would be nice.  Even if the kick/ban/mute hasn't happened yet.

#### Select the type of feature you are requesting:

- [ ] Cog
- [X ] Command
- [ ] API functionality

#### Describe your requested feature

Once a channel has been set for moderation . log:

!bot.modset modlog #moderation-logs

Any deleted message should be logged as long as the deletion is not the original poster.

**Comment by mikeshardmind** [comment]
> I would love the ability to permission users for moderation by role rather then listing users individually.

Can you clarify what you mean here?

Permissions for taking action as moderators is already role based. 

If you instead mean to target an entire role with a moderation action, I think this is out of scope for core red, as usually you don't punish a group for the actions of an individual.

> Also, the ability to modlog a deleted message would be nice.

This seems like a terrible idea. If a message is deleted, it was deleted for a reason. Even putting the privacy issues which could arise from that aside temporarily, this gets into spamming the API. Message deletion has a significantly higher available rate limit than sending messages for a reason.

**Comment by Tobotimus** [comment]
@safaci2000 Just to be clear, if this is a suggestion for V2, V2 is feature-locked.

I'm not sure what you mean by your first suggestion.

As for your other suggestion, deleted messages in the modlog won't be a part of the core bot. In V3, a 3rd party cog could use the modlog's API to log deleted messages, if that was so desired.

I'm gonna close this issue but since we don't really understand your first suggestion, you may clarify what you mean below and if we think it's worth considering we will reopen the issue.
