### ISSUE TITLE
V3 Handler not shutting up after custom error handler.

### ISSUE THREAD

**Issue by locastan** [Cog-Creators/Red-DiscordBot#2276]
# Other bugs

#### What were you trying to do?

Replace a redbot error message (in this case the message displayed after CommandOnCooldown was triggered) with a custom message via @my_function.error:

    @my_function.error
    async def myfunction_error(self, ctx, error):
        if isinstance(error, commands.CommandOnCooldown):
             await ctx.send("I feel a little tired now. Ask me again in {:.0f}s".format(error.retry_after))

#### What were you expecting to happen?

To only see my custom on_cooldown message from the event above.

#### What actually happened?

The bot wrote:
I feel a little tired now. Ask me again in 117s
This command is on cooldown. Try again in 116.69s

#### How can we reproduce this issue?

Add cooldown to any command and extend the @functionname.error handler like I described for your command. Then cause the command cooldown and try to use the command again while on cooldown.

**Comment by mikeshardmind** [comment]
This should probably be handled, but I did forget an option when discussing this with you in discord.

using the special named cog level: `async def __error(self, ctx: commands.Context, error)` will prevent default red messages. since you want this for the specific command, you can make this `pass` if you will handle each command separately, or do all of your command error handling for the cog in here (check ctx for what failed)

**Comment by locastan** [comment]
Replacing the @myfunction.error decorator with this function led to the same result:

    async def __error(self, ctx: commands.Context, error):
        if isinstance(error, commands.CommandOnCooldown):
            await ctx.send("I feel a little tired now. Ask me again in {:.0f}s".format(error.retry_after))
