### ISSUE TITLE
[Mod] Voice checks

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2296]
I'm talking about [these checks](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/cogs/mod/checks.py), there are currently 2 issues with these checks.

The first issue is that these checks **do not** respect Permissions and will ignore allows or denies, since they do not use the core ``mod_or_permissions`` check for example.

The second issue is a bit more ingrained in the checks it self. As soon as these checks come across the first channel in a server that they do not have the permission to mute or deafen members. (for example lets take a channel override deny mute members) The entire check will fail and will return False, leaving the bot unable to actually use the command in that guild at all.

Affected commands:
``mute voice``
``unmute voice``
``voiceban``
``voiceunban``

**Comment by mikeshardmind** [comment]
Not touching that without more discussion, since this would be a potentially breaking change to the RC.

I do agree that the check is currently problematic. Here's what I'd personally do:

1. Remove the check from the commands that use it.
2. Modify the 4 commands that use it to filter applicable channels by permissions bot has, rather than deny if missing on any channel, raising a failure if no channels targetted are allowed.
3. Remove the check, or rename it to accurately describe it's behavior, since most checks behave on context, not on all perms individually resolved for each channel.

Additionally, these checks fail to prevent a 403 error in the case where the bot has the requested perms, but cannot connect to the voice channel, so they do not accomplish what they need to in their current form

**Comment by Tobotimus** [comment]
Resolved by #2351.
