### ISSUE TITLE
Queue list?

### ISSUE THREAD

**Issue by jonyroda97** [Cog-Creators/Red-DiscordBot#257]
It's gone :cry:

**Comment by hillpd** [comment]
If you revisit this -- it would be nice to list the search query for songs that aren't known yet. Previously the queue would post "A Song" for every youtube search because it hadn't fetched the video yet. 

Our group would feed a bunch of songs to the queue and then shuffle -- only to see a dozen "A Song" titles in the list. Listing the query would let us know what's coming up.

**Comment by franc-ist** [comment]
@Zebdan that's one of the features that we decided before rewriting audio that was always gonna be there. We fixed this before the rewrite, and now just need to implement it.

**Comment by tekulvw** [comment]
Added with #294

**Comment by Kowlin** [comment]
ITS DONNEEE

**Comment by jonyroda97** [comment]
YEY!!! :tada:
IT'S BACK!!!
