### ISSUE TITLE
Audio cog clobbers Lavalink.jar on (re)load

### ISSUE THREAD

**Issue by luna-system** [Cog-Creators/Red-DiscordBot#2656]
While testing some issues with the audio cog getting 403s it was suggested that I test with later Lavalink releases. I noticed after some testing that the filesize of the jar was changing and all the sizes were the same. After a bit of digging i found this: https://github.com/Cog-Creators/Red-DiscordBot/blob/5c91709ac8a5096d236420663d334e58f8450488/redbot/cogs/audio/manager.py#L237

Looks like this line is worded to look for outdated versions of the JAR, but actually is just checking for any version that isn't the one targeted. Optimally this will return `true` if the build is equal to _or greater than_ the one targeted, and false otherwise.

**Comment by Tobotimus** [comment]
This was done intentionally for backwards compatibility reasons, but we've decided to ditch it and accept newer builds as up-to-date, since it's probably more common that users need to modify and update their jar than it is for someone to downgrade their bot and find out their newer Lavalink.jar no longer works.
