### ISSUE TITLE
Multiple Improvements to Audio Cog  

### ISSUE THREAD

**Issue by jonyroda97** [Cog-Creators/Red-DiscordBot#271]
- Choose to start a playlist from a specified music (using the number of the music in the playlist)
- Skip a specified number of musics (with warning if there is any user's queued musics in that number of skips and (maybe) the list of musics that will be skipped, if it's a low number)
- Pull queued music to the top of the queue list, to play next (or just a way to order the queue list)
- Have a per username playlists that only them (user, owner and admins) could edit/delete
  (Everyone could play them or not if the user sets it to private or public)

Ps: My english isn't good so... if you don't understand something say and I try to explain :+1:

**Comment by irdumbs** [comment]
I like the playlist thing.

**Comment by irdumbs** [comment]
a few things I'd like to add before I forget.
- !song should display who requested it
- !queue should display how many songs in the queue also
- !search for when you want to play a video but not sure which yet. (gives 1stx hits and lets you choose which to play if any.) (replace !yt functionality with this since !play and !queue already have !yt capability?)
- !playlist by itself displays info about the current playlist, sends cmd help if none playing?

**Comment by Twentysix26** [comment]
I've put it in the general list
