### ISSUE TITLE
Max concurrent audio streams

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#272]
This is more a safety feature. To avoid hardware damage we should make a limit on audio streams the bot can have running at the time. This will avoid 2 things, bottlenecking the bot due to CPU limitations. And possible physical hardware damage due to increase of temperature.

**Comment by Cal9000** [comment]
Your CPU will throttle on its own to decrease temperature, that's not something you need to add to a program. But I agree that it would be nice to limit audio streams to avoid lagging out the bot on a slower CPU.

**Comment by SapphicCode** [comment]
There are hardware sound cards that won't fare as well if they are overheating. More so if the server doesn't have adequate cooling.

**Comment by Kowlin** [comment]
As far as I know, the sound card won't have anything to do with it. Since its just for the encoding. But seems like @tekulvw is making another solution. that strongly reduces CPU usage for cached songs.

**Comment by tekulvw** [comment]
Moving to #623

**Comment by Drapersniper** [comment]
Dependant on #3157

**Comment by aikaterna** [comment]
It feels almost sacrilegious to close a 6 year old issue, but this was opened back in the day when the bot leveraged ffmpeg for audio playback and limiting that memory use was a very valid concern after multi-voice audio was introduced. Fun fact: prior to the multi-voice rewrite, audio was only usable in one server. Period. 

These days, since we use Lavalink, I feel like people can limit memory usage using a maximum memory allocation pool jar flag on launch... that doesn't address the literal issue idea of limiting the amount of connected players but since memory concerns were the other half of this issue, I'll leave it at this for now.
