### ISSUE TITLE
Logging Format

### ISSUE THREAD

**Issue by SomewhatDamaged** [Cog-Creators/Red-DiscordBot#2782]
# Other bugs

The logging format was changed from:

`"%(asctime)s %(levelname)s %(module)s %(funcName)s %(lineno)d: %(message)s"`

to

`"[{asctime}] [{levelname}] {name}: {message}"`

Not sure why this was done, but it makes debugging with the built-in Red logfiles much harder. Any chance of having module/function/line# added back to the logfile outputs?

**Comment by Kowlin** [comment]
I'm not sure what's causing this but the last change to the logging system that touches the way it prints the logs was 3 months ago with #2502. So this may be something on your side, also checking my own logs and it appears that it correctly follows the given format

``Jun 21 15:31:08 modbot1 redbot[1162]: [2019-06-21 15:31:08] [WARNING] discord.state: VOICE_STATE_UPDATE referencing an unknown member ID: 581806909284286465. Discarding.``

**Comment by SomewhatDamaged** [comment]
All I get in the red.log logfile is:

`[2019-06-21 21:52:04] [ERROR] red.imagesafe: <class 'concurrent.futures._base.CancelledError'>`

**Comment by Tobotimus** [comment]
The reason this was done is because logging is seen by both users and devs, and the module/function/line number made the logging messy. 

The log name was added because it's usually a clear indicator of what module the log came from.

In my opinion, if you're using log messages for debugging your code, but you don't know which line the log message was emitted from... Use clearer log messages. Or if you really want the old behaviour, you can change the formatter for your logger exclusively. I never came across anyone who found the module/function/lineno useful, but I'm sorry it has been an annoyance for you.

**Comment by SomewhatDamaged** [comment]
Fair enough. I wasn't sure if this was an intended change or not. Thanks for the quick turn-around.
