### ISSUE TITLE
Use  `ctx.maybe_send_embed` where possible

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#2859]
# Feature request

- [ ] Cog
- [ ] Command
- [ ] API functionality
- [x] Enhancement

#### Describe your requested feature

Think we should where possible use `ctx.maybe_send_embed` where possible instead of the normal `ctx.send` in some parts of the code we do one and some parts we do the other.

This would allow users to have a bot thats mostly embeds if they so which to enable embeds for their bots, and I feel this would help us standerdise a major user facing function (sending messages)

Making this to get the conversation flowing and if we come to an agreement I can go over Red's source code and  switch `.send` for `maybe_send_embed`

**Comment by Zephyrkul** [comment]
Potential issue with this is that we could lose some important features like mentions if we blindly switch everything over to maybe_send_embed. Every switch we make should be made with that, and any other potential downsides, in mind. As well, with maybe_send_embed, the page length becomes 2048 rather than 2000 (due to embed descriptions having a higher max length). This could be left alone in cases where pagify is used since it's a small difference but it's worth pointing out regardless.

**Comment by mikeshardmind** [comment]
This has come up a few times before. Embeds can and should be used where they make things clearer and the user has them enabled. If embeds do not make things clearer, they should not be used. A reliance on discord's embed proxy for every single response doesn't make sense.

A user setting "use embeds" does not mean embeds should always be used, just that they should be used when there is a choice, same for not using embeds (see the audio cog for where this goes the other direction)
