### ISSUE TITLE
Streams Role

### ISSUE THREAD

**Issue by naitoshedo** [Cog-Creators/Red-DiscordBot#2893]
# Feature request
- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature

It would be really awesome if the streams cog would add / remove a role to someone does the stream detection. All streamer role cog stuff I've found so far relies upon the person's profile being detected as streamer mode (which is rather flawed as all they have to do is alt tab to something else like Spotify and the role is removed).

**Comment by Menteroth** [comment]
Streamer mode in Discord is enabled when you have OBS/XSplit running. And for the user to get 'streaming' presence the channel must be live. Alt-tabbing doesn't change anything. It's just Spotify overwriting the previous presence.

Unlink Spotify from Discord for now. Since Spotify overwrites 'streaming' presence for some reason.

**Comment by Drapersniper** [comment]
I also done a PR to to the 2 verified steamrole cogs to support streamer roles on non primary actions, in case you want to follow them.

tmercswims/tmerc-cogs#96 and Tobotimus/Tobo-Cogs#54

in case the Cog creators wish to support background streaming activities.

**Comment by mikeshardmind** [comment]
This is supported by available approved 3rd party cogs, we don't have a compelling reason to absorb this behavior into core.
