### ISSUE TITLE
Reserve [p]cancel

### ISSUE THREAD

**Issue by Zephyrkul** [Cog-Creators/Red-DiscordBot#2973]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature

Reserve a no-op `[p]cancel` command, which is currently used by the built-in [cancelled predicate](https://red-discordbot.readthedocs.io/en/stable/framework_utils.html#redbot.core.utils.predicates.MessagePredicate.cancelled), in the core cog, with a valid docstring, in order to prevent surprising behavior from other third-party cogs registering that command.

**Comment by mikeshardmind** [comment]
Rather than reserving a command here, it might be better to forbid the use of a list of strings as command names or alises and raise an error explaining this when someone attempts to create a command named as such.

This prevents us from dispatching on a no-op while still preventing the surprising behaviors.
