### ISSUE TITLE
[Core] Infinite typing when calling command within last second of cooldown

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2985]
# Other bugs

#### What were you trying to do?

Use a command with cooldown within last second of cooldown.

#### What were you expecting to happen?

Either get a cooldown message or have the command reinvoked (thinking of the latter because that's what it should by looking at the code)

#### What actually happened?

Infinite typing of a bot until you run that same command again.

#### How can we reproduce this issue?

1. Use a command with cooldown.
2. Use a command with cooldown again within last second of cooldown.

Code with the issue: <https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/core/events.py#L235>

**Comment by Jackenmen** [comment]
Oh and also typing shouldn't really be in there at all as the invoked command should be the one to handle it if it wants to.

**Comment by mikeshardmind** [comment]
If I recall correctly, the typing there was so that users knew *something* was going on during that delay.

Bot shouldn't be typing infinitely there though. 

The problem with using typing is that discord only allows you to start typing. 10 seconds after that, or when you send a message, it stops being rendered as "[user] is typing" and not all commands will send a message.

**Comment by Jackenmen** [comment]
Yeah, though that delay should be less than second and I don't think triggering it is really needed there. The actual problem though is that due to way cooldown is handled in d.py we can't (easily) invoke the context again as cooldown is checked with time when message was sent.
I would just go with removing the whole less than a second handling and just regularly show that you should "try again in 1 second"
