### ISSUE TITLE
[Trivia] whosthatpokemon - tinypic urls missing

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#3023]
# Other bugs

#### What were you trying to do?

Play trivia with the whosthatpokemon list.

#### What were you expecting to happen?

For a silhouette of a pokemon to show.

#### What actually happened?

The image is gone.

#### How can we reproduce this issue?

Play trivia with the whosthatpokemon list and have it show any tinypic url.

**Comment by mikeshardmind** [comment]
If we have the originals for some of these trivia lists, we should try and have them uploaded on a long term host okay with hotlinks, such as imgur, on an account controlled by the organization, while keeping the originals for reupload if needed.

**Comment by aikaterna** [comment]
I have an archive of 151 gen 1 images I can convert to shadows/completely black and provide to whomever in the Red server if needed.

**Comment by Jackenmen** [comment]
Maybe we could put them on GitHub (in separate org repo) and use cdn like jsdelivr.com/raw.githack.com/statically.io/etc to hotlink the images in trivias?

**Comment by Kevin-Mok** [comment]
So, @Redjumpman has a Pokedex cog that has a [CSV file](https://github.com/Redjumpman/Jumper-Plugins/blob/V3/pokedex/data/Pokemon.csv) containing all the Pokemon names along with URL's to their images. The problem is that the URL's contain the Pokemon names in the URL, so you can't directly use them in the YAML file for the question. I extracted the relevant information from the CSV in this [text file](https://github.com/Cog-Creators/Red-DiscordBot/files/3967278/pokemon-name-image.csv.txt) (added `.txt` to end since GitHub doesn't allow attaching CSV files).

I was thinking if we could embed the image in the trivia question like @aikaterna does in their [inspirobot cog](https://github.com/aikaterna/aikaterna-cogs/blob/v3/inspirobot/inspirobot.py#L12-L24), then that'd be great. But, that would require rehauling how the YAML file is parsed, which seems like it could be annoying. Does anyone have any thoughts on this?

**Comment by Drapersniper** [comment]
Aika is in the progress of updating the urls host afaik. 

The trivia cog doesn’t have permissions to explicitly enforce embeds the only cog in core that has such permission is Audio due to its UX. even embedding these images provided does provide the users with the ability to cheat by checking the image url (if I understand what you’re saying I.e use RJM images)

**Comment by Kevin-Mok** [comment]
Oh, okay. That's good. Also, I didn't realize you could check the image URL from the embed. :sweat_smile: I thought it uploaded it to Discord like how Pokecord does it which would obscure the name.

**Comment by Drapersniper** [comment]
Only way to get it to work without giving the answers  is bundle the RJM images without names but that would require a restructure of how Trivia parses the question so that it can attach bundled images. but imo just rehosting the images like @mikeshardmind  suggested would be the best option and require no rewrite.

**Comment by Kevin-Mok** [comment]
I talked to @aikaterna about taking this over. My current plan is to write a script to:
- [ ] download all the 1000 Pokemons from [RJM's Pokedex CSV](https://github.com/Redjumpman/Jumper-Plugins/blob/V3/pokedex/data/Pokemon.csv)
- [ ] convert them to a silhouette with a white background (or send them to aikaterna to do so)
- [ ] upload them to Imgur while adding their direct image URL to [my modified CSV](https://github.com/Cog-Creators/Red-DiscordBot/files/3967278/pokemon-name-image.csv.txt)
- [ ] create YAML trivia file from CSV

We were also talking about splitting up the Pokemon trivia list into each generation since we're thinking that not everyone is interested in learning/guessing a lot of the newer generation Pokemon. I was initially thinking of creating a list for each generation, and people could specifically choose which generation category they want to play.  However, aikaterna mentioned that this would be pretty cluttered, and I think I agree. So, should we group some of the generations together, or how do you guys think we should do it?

**Comment by skylarr1227** [comment]
Can I just say, that from our Pokemon bot and my work with mewbot.... I have all the images hosted, in both named and numbered format, separately, and even with dynamic hashed links to prevent easy recall of the number by bot or person. Just saying. IDK if it helps.

**Comment by skylarr1227** [comment]
And I mean including generation 8 Pokemon.

**Comment by skylarr1227** [comment]
If you do want/need this...  Let me know

**Comment by Kevin-Mok** [comment]
@skylarr1227 That sounds like it would be a major help. Could you DM on Discord at PistolFist#9148?

**Comment by skylarr1227** [comment]
Absolutely

**Comment by skylarr1227** [comment]
I added you, Name is Sky ..  just shoot me a message sometime

**Comment by Kevin-Mok** [comment]
I think I accidentally declined your request since I saw the request before seeing this response... :sweat_smile: In any case, I guess we should discuss the matter here for transparency anyway.

I realize that your current hosted images may not be as helpful as I initially thought since @aikaterna mentioned that the Pokemon pictures for the trivia should be silhouettes. As such, we would need the image files directly to convert them. Do you still happen to have the all image files locally?

**Comment by skylarr1227** [comment]
yes, I do. Also, i showed that it was possible to show them in a way that
makes it nearly impossible to to cheat.

**Comment by aikaterna** [comment]
The images should be under control of the Cog Creators org and we shouldn't be relying on an outside hoster. I realize trusting them to imgur, which was my original intent, isn't exactly "under the control of" the org, but it's a business with expected uptime and deliverability so I would want the images hosted on that sort of site since the entire user base would be relying on that. Skylarr, if you want to provide the images to us we will make them suitable for the trivia as it existed before (white background, black shadow pokemon image). 
As for multiple generations in one file, there may need to be some discussion about having pokemon trivia broken up by generation as people could play what gens they want, or all, at the same time: `[p]trivia whosthatpokemon1 whosthatpokemon2 whosthatpokemon3`, etc.

**Comment by aikaterna** [comment]
Since this discussion has become stale, I am intending to move forward with replacing the original 1-151 images on our existing trivia file for this item and further generations/trivia files can be discussed in another issue or in a PR.

**Comment by Pyroptical** [comment]
remade from scratch with updated image urls added up to gen 4 and made the images into the format of the original show
[whosthatpokemon.txt](https://github.com/Cog-Creators/Red-DiscordBot/files/4708129/whosthatpokemon.txt)
