### ISSUE TITLE
[Core] Users may accidentally lock guild owner and themselves with `[p]localwhitelist add`

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3222]
# Command bugs

#### Command name

`[p]localwhitelist add`

#### What cog is this command from?

Core

#### What were you expecting to happen?

I was expecting to get an error saying that I can't lock out myself (and guild owner) from using the bot.

#### What actually happened?

I locked myself and guild owner out.

#### How can we reproduce this issue?

1. Have permissions to use `[p]localwhitelist` (e.g. have admin role), but don't be bot owner.
2. Use `[p]localwhitelist clear`
3. Use `[p]localwhitelist add SOMEONE_ELSES_USER_ID`

---

This doesn't seem like a trivial task but it would surely be great to have it improved.

**Comment by mikeshardmind** [comment]
We can't escape this case in any good way at the command level. We can do like with bot owner and the global list, and at least exclude the guild owner from being checked by local whitelist/blacklist so that there's always at least 1 authoritative person with a way to fix that specific issue.

While it would prevent a bot owner from localblacklisting a guild owner, I'd argue the bot owner has more powerful tools such as blacklisting the entire server, leaving a server, or the global bot settings. for blacklisting

**Comment by Jackenmen** [comment]
~~This issues has been in triage status for a while, and it really needs some fix.~~

~~PRs excluding guild owner from local whitelist/blacklist checks are very much welcome.~~

Looks like the important (the more trivial) part of this issue has already been fixed.

It would be awesome if the commands were "smart" and knew whether you would lock yourself out when running them but it's not trivial and since there is at least one person in the guild who can still fix the localwhitelist problem, it isn't a priority.

**Comment by Jackenmen** [comment]
Looks like the part that badly needed the fix was already fixed around the time this issue was created. I updated my previous comment to reflect this.
