### ISSUE TITLE
modlog.create_case() should raise exception not fail silently when passing invalid action_type

### ISSUE THREAD

**Issue by Bakersbakebread** [Cog-Creators/Red-DiscordBot#3346]
Current behaviour is to `return None` when an invalid `action_type` is passed.

```py  
 # redbot/core/modlog.py
case_type = await get_casetype(action_type, guild)
    if case_type is None:
        return
```
[Quick link](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/core/modlog.py#L750)

**Comment by mikeshardmind** [comment]
Not sure I agree with that, but changing that would be breaking so there's plenty of time for that to be discussed.

**Comment by Jackenmen** [comment]
While it could be a tiny bit better (easier to detect a problem in your code and more Pythonic perhaps) if this raised an exception, it returning `None` is documented quite clearly and there's only one case it can return it in so I don't think it warrants possibly breaking someone by it just to make the API a bit cleaner.

**Comment by Jackenmen** [comment]
> While it could be a tiny bit better (easier to detect a problem in your code and more Pythonic perhaps) if this raised an exception, it returning `None` is documented quite clearly and there's only one case it can return it in so I don't think it warrants possibly breaking someone by it just to make the API a bit cleaner.

This comment of mine doesn't make a lot of sense 🤔 I think I thought that this issue is referring to `modlog.get_casetype()`, not `modlog.create_case()`... So ignore my previous comment as I think that this DOES make sense to do as the breakage is minimal and I doubt that anyone would intentionally pass invalid action type to `create_case()`.

With that out of the way... This should be quite simple, it just requires raising `ValueError` rather than returning. PRs are welcome.
