### ISSUE TITLE
[Downloader] Reload with cog update parameter

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#3539]
A way to allow cog updates to reload cogs upon updates without prompting, can be something like `[p]cog update -y` that would auto reload all cogs updated.

**Comment by Vexed01** [comment]
What is people's opinion about adding this as a optional subcommand eg `[p]cog update reload [optional specific cogs]`? (like trivia)
In my head it should be possible to handle a cog called "reload".

**Comment by Jackenmen** [comment]
Red 3.4 will already disallow cogs with hyphens (see #3605 and implementation in #3679) so using flags would save us from making yet another breaking change when we would have to reserve `reload` cog name. Considering this is an additional enhancement for those who want to use it and that Downloader can only be used by bot owner, using argparser-like flags seems like a more obvious choice.

From other things:
- we have multiple update commands, so each would need this subcommand added
- *if* we would want to allow the user to change the behavior to "reload unless -n flag is passed" via setting, it wouldn't be as obvious that `[p]cog update reload` has to be used to *not* reload
- there are more things that are gonna need flags anyway - namely #2084, but possibly also #3446 

Let me also mention that I was planning on pursuing this stuff myself when my break is over.

**Comment by Vexed01** [comment]
I'll leave it to you then 😄

**Comment by RheingoldRiver** [comment]
Is there any progress on this? We just had a critical bug exist in prod for an extra 24 hours because I accidentally didn't reload after updating cogs, and this isn't the first time something like this has happened (tbh it's pretty common, this is just the most impactful it's been in months). It's really, really easy to forget to idle in the channel for an extra 30-45 seconds for large cogs and then accidentally not have a change loaded.
