### ISSUE TITLE
Stop showing DeprecationWarnings from all modules by default

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3612]
This provides no useful info for the end user, and it only causes noise and confusion to be generated

As such the current behaviour should be hidden behind the `--debug` flag
https://github.com/Cog-Creators/Red-DiscordBot/commit/42a4d10ea5ed0d8f337edb73a2c8a3c60e162aaa#diff-3b9bdb4dfee95e89963ffdc7160a5a6fR200 should use 

```py
if "--debug" in _sys.argv:
    _warnings.filterwarnings("default", category=DeprecationWarning)
```

**Comment by Stonedestroyer** [comment]
I will shortly PR this.

**Comment by Jackenmen** [comment]
I have a feeling, it might be better to filter the specific warnings that we can't solve because they occur because of our current dependencies and mark them with `# DEP-WARN` so that we can look if they got addressed each time we bump dependencies.

While you are right they are just warning and they might not give much information to the user, they are things that **should** be fixed. And if users see them, they will be able to come to us and therefore let us know they exist. This is in my opinion a lot better than letting them get by silently because of nobody knowing they occurred.

Warnings filters are quite powerful and each entry in warnings filter list can specify any of these:
- a regular expression that the warning message must match
- warning category (i.e. `DeprecationWarning`)
- a regular expression that the module name must match
- integer that the line number where the warning occurred must match

---

I'm putting this up as a possible alternative way of handling this, I don't have much problem with the solution proposed here, just thinking there might be some advantages to the one I proposed here (though there are some disadvantages too - like having to update the filtering on dep update and also when someone finds an unfiltered warning that needs filtering in logs too)

**Comment by Stonedestroyer** [comment]
Would filtering the warnings for non debug and showing all warnings for debug be a good solution?

**Comment by Stonedestroyer** [comment]
#3615 is an alternative.

**Comment by Drapersniper** [comment]
Before deciding the route to take here, it would be great hearing users feedback.

Does the community feel that the DepricationWanings provide them with any benefit ? 

Here is an example of the warnings I mean.
https://gist.github.com/MatrixSouler/ed7d74b0f6911b3b3b92ca631a4d0a40
And the ones in https://github.com/Cog-Creators/Red-DiscordBot/issues/3529

Note that these could change overtime as things become depricated.

Let us know so we can decide where to put this output behind the `--debug` flag or still show them to all users.

**Comment by Bakersbakebread** [comment]
If they are relevant to third party code then Deprecation Warnings are only noise since they are not the end users responsibility to fix.

Hiding it behind the `--dev` flag ensures that only those who want to see the warnings can see them, one would hope that the test framework will enable these warnings too.

**Comment by Twentysix26** [comment]
I think filtering only known warnings is the more sensible solution (#3615). Having users being able to report new warnings to us is valuable and so is having warnings show up in case third party cogs use deprecated core functions.

**Comment by Jackenmen** [comment]
We can reiterate this at later date if proved problematic, for now we decided to choose #3615, we also asked about this in #v3-burndown on Red server and most people did choose this option too.
