### ISSUE TITLE
[p]local folder can't play folder with ASCII characters, but can play ASCII characters song

### ISSUE THREAD

**Issue by namkien04** [Cog-Creators/Red-DiscordBot#3789]
# Command bugs

<[p]local folder <folder name> 
Did you find a bug with a command? Fill out the following:
-->

#### Command name

[p]local folder <folder name>

#### What cog is this command from?

 audio 

#### What were you expecting to happen?

 to play folder that have ASCII characters in it 

#### What actually happened?

 it reports as "nothing found", although it can play song with ASCII characters in another folder with non-ASCII characters just fine (ex: folder name is linhtinh, the file name is 001-イニシャル.flac, nothing wrong with it, the bot play the file just fine; folder name is [Hi-Res][mora自购]roselia一专 anfang, the file name is 004-陽だまりロードナイト.flac, "nothing found" error appeared)

#### How can we reproduce this issue?

1) create folder with non-ASCII characters name in localtracks
2) use "[p]local folder <folder name>" to play folder

**Comment by aikaterna** [comment]
Hi namkien04, we have had a significant audio rewrite merged after your issue was opened. I followed your instructions in making a folder named "[Hi-Res][mora自购]roselia一专 anfang" and having a file in that folder named "004-陽だまりロードナイト.flac" and it worked with the local folder command and the local play command. Can you please make sure you are updated to Red 3.3.9 and give this a try again? If you do have the same issue, can you please provide folder names and files that don't work? I will be closing this issue in 7 days otherwise if we don't hear from you.

**Comment by namkien04** [comment]
Maybe at that time I was at the outdated version, but now it worked, thanks

Vào 06:20, T.4, 17 Th6, 2020 aikaterna <notifications@github.com> đã viết:

**Comment by aikaterna** [comment]
Glad to hear it. Thank you for the info.
