### ISSUE TITLE
[Breaking][Config] Restrict config value types to be compatible with ujson

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3858]
One type that comes to mind currently is ensuring integers are smaller than 2^64.

**Comment by mikeshardmind** [comment]
Is it worth breaking users instead of pushing them to use a different backend? If it is, why not something faster such as orjson or even simdjson?

**Comment by Drapersniper** [comment]
Ujson was my mention here for availability, wheel for window will be out soon if it's not already, the whole push behind this one is aReJson driver 64-bit limit on ints , but ... if orjson was readily available to all system we support id prefer going with that. Simdjson never heard of it.

**Comment by Jackenmen** [comment]
There's certainly some rules about allowed floats in ujson too, I know for sure that NaN and (+/-)inf don't work but there might be more restrictions.

We should also take a stance on what features of the library we choose are implementation details, for example: `ujson` allows custom objects to define `__json__` returning JSON string but no other json library does this which could lock us out if we don't say it's implementation detail.

**Comment by Tobotimus** [comment]
If this breaking change was purely for the integration of ujson, I wouldn't accept it.  
Unless there was some *proven* big speedup, with numbers specific to our bot's performance, it wouldn't be worth the breaking change.

However, ujson aside, 64-bit integer restriction in config and some similar one for floats *may* be worth looking into if we finally want to take care of `inc()`. At the moment I believe the postgres driver casts a JSON int into a bigint before doing any arithmetic, so naturally the int size is restricted to signed 64-bit there, if we enable `inc()`. Undoubtedly some other drivers would bring a similar restriction if they included native `inc()` functions.

Overall I also think this would just improve consistency across future backends, since this restriction is not uncommon (take MongoDB for example).
