### ISSUE TITLE
[Audio] `[p]skip` when paused briefly plays

### ISSUE THREAD

**Issue by Vexed01** [Cog-Creators/Red-DiscordBot#3918]
# Command bugs

#### Command name

`[p]skip` (when invoked after the music is `[p]pause`ed)

#### What cog is this command from?

Audio

#### What were you expecting to happen?

After the music has been paused, I was expecting `[p]skip` to start playing the next track immediately.

#### What actually happened?

After the music had been paused, the paused track restarted playing briefly before the next track started.

#### How can we reproduce this issue?

1. `[p]load audio`
2. Play at least two tracks - this could be a playlist or two individual tracks.
3. Run `[p]pause`
4. Run `[p]skip`

To clarify, _the music un-pausing after `[p]skip` is not the issue_, the issue is that the paused track plays for a second or so before the next track starts.

Make sure you have sound on to hear this: https://videobin.org/+19n1/1fwt.ogg (yes I queued the same song twice)

**Comment by Drapersniper** [comment]
This is caused by the `play` op send to Lavalink  by RLL.

This appear to be an issue with the server itself and not RLL or Red.

Will keep it open for now, until i get more info here.


for context:
```py
        await self.send(
            {
                "op": LavalinkOutgoingOp.PLAY.value,
                "guildId": str(guild_id),
                "track": track.track_identifier,
            }
        )
```
Is the OP that causes it to resume play before starting next track if the current state is paused.

**Comment by Drapersniper** [comment]
![image](https://user-images.githubusercontent.com/27962761/83964184-10032a80-a8a3-11ea-8ff6-eb63fdbf325b.png)
so this is untestable on older lavalink build.

But one say i can say with certainty is that this is not caused by Audio, Red or RLL.

**Comment by aikaterna** [comment]
After testing a bit and drilling down on this...
It is not the Lavalink jar (both Magma and Koe-based Lavalink jars responded the same, so it is not the internal sound sending system)
RLL sends OPs of play -> pause -> play during testing this behaviour
Wavelink sends OPs of play -> pause -> stop -> play, not displaying this issue.
I'll leave it up to Draper in how to handle it but as we're talking about it, we will most likely make Audio call stop on a skip like Wavelink's behaviour so that the blip of sound isn't heard.
