### ISSUE TITLE
[Audio] YouTube playback failure 

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3943]
This is an informational issue.

Currently there is some known issue happening with youtube and your bot may not be able to play any tracks.

Please to keep the amount of spam low, no need to update this issue letting us know you are experiencing it. we are aware of the issue and looking for a fix.

**Comment by aikaterna** [comment]
Youtube seems to be testing a new style of response from their site lately and occasionally users will get "Nothing Found" when trying to play a song. Trying again usually works. This issue is on the radar of the project that manages the audio backend we use and things will be updated on our side when we have an update to publish.

**Comment by aikaterna** [comment]
Should be resolved with the Red bump/update.
