### ISSUE TITLE
[Audio] Should Audio auto deafen the bot when it joins a VC?

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3996]
Making this to hear from prople.

Currently d.py and in turn Red does not have any way to receive audio from VCs but some users don't care about that and as skeptical about their privacy.

So my question is should we set the bot to auto deafen itself the moment it joins a VC, it would be a rather trivial change to make this happen, but will only do it if theres enough agreement and demand for it.

**Comment by flaree** [comment]
I'm in favour of the auto deafening itself on join, I've had users ask me if there was any recording of voice etc and a lot of servers I use have it deafened.

**Comment by mikeshardmind** [comment]
I can't see any downside to this which doesn't involve discord.py *having* voice receive.

That is, this shouldn't remove anything people could do with the bot such as use it to host and record an (intended) publicized chat because the bot doesn't have that capability anyhow.

Even though we all (here) know the bot can't get audio currently, it's a trivial change with no obvious downside which makes users feel more at ease.

**Comment by PredaaA** [comment]
> I'm in favour of the auto deafening itself on join, I've had users ask me if there was any recording of voice etc and a lot of servers I use have it deafened.

Same thoughts for me.

**Comment by aikaterna** [comment]
+1 on the idea here

**Comment by Drapersniper** [comment]
This has been implemented on audio version 2.4.0
