### ISSUE TITLE
` ctx.clean_prefix` sanitizes only bot's mention (documentation issue)

### ISSUE THREAD

**Issue by fixator10** [Cog-Creators/Red-DiscordBot#4122]
# Other bugs

#### What were you trying to do?

Sanitize mentions with `Context.clean_prefix`

#### What were you expecting to happen?

All mentions are sanitized to `@%display_name%` state

#### What actually happened?

Only bot's mention sanitized

---

As explained in the comments below, this is a documentation issue.

**Comment by Jackenmen** [comment]
This is a documentation issue, not a bug with the `Context.clean_prefix`.
Docstring should be made a lot clearer:
a) rather than saying that it makes a mention prefix "display nicer", it should say that it's a prefix with bot mention sanitized (could possibly be worded even better than that)
b) it should specify that it's only sanitizing mentions of bot user
c) it should (imo) say some intended use case, i.e. that it should be used instead of `ctx.prefix` in places where discord mentions aren't rendered
