### ISSUE TITLE
[API] add ability to check for disabled command

### ISSUE THREAD

**Issue by fixator10** [Cog-Creators/Red-DiscordBot#4130]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature

Add ability to check if command is disabled. E.g. via command property `is_disabled_globally` and func `is_disabled(ctx)` or smth like that.

**Comment by oyie1** [comment]
Hi! I am interested in working on this. Can I be assigned to this please?

**Comment by Jackenmen** [comment]
Sure, I've assigned you.
For your information, it's already possible to check whether the command is disabled using the `command.enabled` attribute so that part is already covered by our APIs and you should only need to implement a way to check whether a command is disabled in a specific guild.
I think a preferred design would be to put a method for checking this in the Command class with the name `is_disabled_in_guild()` and have it accept a `discord.Guild` object as a positional-only argument.
