### ISSUE TITLE
[p]volume crashes lavalink

### ISSUE THREAD

**Issue by vilgotf** [Cog-Creators/Red-DiscordBot#4520]
# Command bugs

#### Command name

`[p]volume <int>`

#### What cog is this command from?

Audio

#### What were you expecting to happen?

The volume to be changed to said percentage

#### What actually happened?

Audio stoped and crash dump got generated: [dump.txt](https://github.com/Cog-Creators/Red-DiscordBot/files/5425674/dump.txt)

#### How can we reproduce this issue?

`[p]play <something>` then (during playback) change volume with `[p]volume <int>`

I've also had some random crashes (generating dumps of the same kind) but now I think those too were caused by having volume be non-100 (although I didn't change the volume during playback)

**Comment by aikaterna** [comment]
You're running it on an alpine based environment which is not supported (musl instead of glibc). If you would like to see support for this, please open an issue in sedmelluq/lavaplayer on github. Alternatively you can run your own Lavalink.jar on a glibc environment instead of using it on the same vps as the alpine/musl one. If you would like more information about this in general, I can chat with you in the Red support server on Discord (discord.gg/red).

**Comment by vilgotf** [comment]
I can personally say that the python base works perfectly and that the rest of the Audio cog seems to be working flawlessly on musl. You should imo reconsider officially supporting musl (and alpine), especially since (official) docker support is planned

**Comment by aikaterna** [comment]
It is not our software, which is why I asked you to open an issue in the lavaplayer repo. The code that determines what natives to load does not discriminate between a glibc environment and a musl one and we will not be able to change that for them.

**Comment by aikaterna** [comment]
I'm under the impression there is also a JDK for alpine that does not use musl, as well.

**Comment by Drapersniper** [comment]
I just wanted to put this out there so that there is no misunderstanding here. The planned docker support does not mean we will be supporting musl or alpine, there is no plans to currently or in the near future to support alpine, the docker images will likely be build based on one of our currently supported OSs. We haven't discussed exactly what OS, but I can say with certainty it will not be alpine.

**Comment by vilgotf** [comment]
The base (without cogs) works 100% on alpine, audio seems to work except `[p]volume`. I'm just saying, Alpine already supports most use cases (and most external cogs are in python, i.e. libc independent)

**Comment by Drapersniper** [comment]
So core red doesn't work 100% on alpine, so alpine can't be supported. It's as simple as that. There's fair more issues given reds modularity hence why we will not be supporting alpine.

**Comment by Drapersniper** [comment]
Fwiw, just because it work "100%" for you environment doesn't mean it will work "100%" for every user. Which is something we need to take into consideration. But this is going off topic from this closed issue. Hopefully the answer here are sufficient, if you wish lavalink to support musl and alpine please do what Aika suggested as that is beyond our control.
