### ISSUE TITLE
[Audio] Shutdown lavalink when not in use

### ISSUE THREAD

**Issue by vilgotf** [Cog-Creators/Red-DiscordBot#4522]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

Lavalink consumes a *lot* of ram (200MB RES) so only having it running when it's needed would drop memory usage.
*(Red [python] uses around 50MB for me, so this would reduce memory usage by 80%)*

Example use case: user is running Red on AWS or another cloud service provider that charges them per memory used, and music is played for ~1 hour per day.

**NOTE**: I'm not suggesting that this should be default, just that it could be an option

**Comment by Drapersniper** [comment]
So the ram recommendation currently for red is you plan to use Audio is 1GB. And 512Mb is you don't use Audio, so the user has the option to not use audio if they are that constrained.

As far as the internal manager goes we will not be setting it to only work when needed,  however since lavalink it's a service dependency and not actually part of red you are free to run an external server that you can turn on or off whenever you wish.

When working on the rewrite we had Two things we considered, having the server always running in the background as part of the API, or lazily start up when something needs to access  API. Due to the nature of how the internal server works it's not realistic to turn off the lavalink server then start it up from scratch when required.

**Comment by Drapersniper** [comment]
Due to having to support all systems we currently support. Since some systems can take 2-4 minutes to start up the internal manager, starting it on demand is not realistic.

Thats said something that is being considered is getting rid of the internal manager all together and let the user handle the LL server themselves, this is being considered for the rewrite.

**Comment by vilgotf** [comment]
When is the rewrite planed /where can I read more about the rewrite?

**Comment by Drapersniper** [comment]
https://github.com/Cog-Creators/Red-DiscordBot/labels/Category%3A%20Audio%20API
https://github.com/Cog-Creators/Red-DiscordBot/labels/Category%3A%20Audio%20Cog

And When I finish writting it.
