### ISSUE TITLE
[Core] Add "competing" as a status that can be used.

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#4607]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command 
- [ ] API functionality

#### Describe your requested feature

d.py 1.5 include a new kind of activity called "Competing". Since `[p]set` already have all kind of activity that can be set on Red, this option should be added. (Maybe as `[p]set competition` or simply `competing`)

**Comment by Jackenmen** [comment]
Makes sense to me, should be added under `[p]set competing` command name to be consistent with the rest of the command names for setting statuses.

PRs welcome! ❤️ 

---

We also need to add this new type of activity to the `[p]userinfo` command. This can either be done in same PR or a separate one. Please don't mark your PR as fixing this issue if you only do one of these things so that it's not forgotten about because of issue closing automatically, thanks!

**Comment by Jackenmen** [comment]
The originally requested feature has been added in #4609. The issue with `[p]userinfo` has been moved to a new issue: #4610 so this can be closed.
