### ISSUE TITLE
Better error message for a command

### ISSUE THREAD

**Issue by ThatDevSebastienM** [Cog-Creators/Red-DiscordBot#4617]
# Command bugs

#### Command name

hackban

#### What cog is this command from?

admin

#### What were you expecting to happen?

Give me a better understanding of why this error occured.
It should let me know that the user ID that I provided was incorrect and I should grab the persons userID again.

#### What actually happened?

If you do the command (ex. !hackban 16125326)
It throws out this message: https://i.imgur.com/n7V1vmQ.png
The reason why the ban wasn't successful is that the user ID was invalid. Wasn't enough numbers. 

#### How can we reproduce this issue?

!hackban or ban a shortened user ID

![4sAjxU4](https://user-images.githubusercontent.com/56210238/99343402-c9efc100-285b-11eb-8466-ba4d049b95a0.png)

**Comment by phenom4n4n** [comment]
This isn't possible to do due to d.py's way of handling of Greedy arguments.

**Comment by Rapptz** [comment]
There is a parsing ambiguity with the way the code is set up. Since the signature is as follows:

https://github.com/Cog-Creators/Red-DiscordBot/blob/a7ec40664e22bbddafcf50bcf17e967204f00c1e/redbot/cogs/mod/kickban.py#L369-L376

The `RawUserIds` conflicts with the `int` signature that follows afterwards. 

However, this parsing ambiguity is not unsolvable if we take advantage of the fact that days can only be specific values, so we can rewrite it to use a new converter instead that checks for this:

```py
class Days(commands.Converter):
    async def convert(self, ctx, argument) -> int:
        try:
            value = int(argument, base=10)
        except ValueError:
            raise commands.BadArgument(_("Invalid days were passed"))
        else:            
            if value not in (0, 1, 7):
                raise commands.BadArgument(_("The number of days must be 0, 1, or 7"))
            return value
```

Note that even though the parsing ambiguity can be solved, the error that'll be reported will be nonsensical since following these changes you'll get the same message and `reason` will become `16125326 whatever` instead. I can't really see a good way to make this error any better to the user with the way the signature is currently set up unfortunately.

**Comment by Flame442** [comment]
Due to a lack of activity, and since there is no good way to solve this issue without adding unnecessary code complexity, I am closing this issue.
