### ISSUE TITLE
Custom Commands Ping Roles

### ISSUE THREAD

**Issue by Oyplap** [Cog-Creators/Red-DiscordBot#4633]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

Can you allow Custom Commands cog to ping roles?
     
Kind regards,
Oyplap

**Comment by Dav-Git** [comment]
That sounds incredibly dangerous. Especially with cc's that use user provided arguments. Accidental or harmful role pings would be greatly facilitated by this.

**Comment by Drapersniper** [comment]
I'm not personally in favour of this, if this is the default behaviour. However a per server setting allowing pings on custom commands is not something I'm agaisnt. (Which is off by default.)

**Comment by Oyplap** [comment]
Some versions ago it was the default behaviour. My server made good use of pinging roles. But im also not against a setting to enable cc pinging roles

**Comment by Drapersniper** [comment]
Yeah it was intentionally changed when discord changed the logic of pings to allow role pings that bypass wether a role is ping able or not.

The above is why it's a no from me to make this the default behaviour, as it was intentionally changed to not work.  But yeah a per server setting that's off by default that server admins can configure to allow the bot to ping roles would be okay since they are opting in imo.

**Comment by Flame442** [comment]
See #2608 for previous discussion on a similar request. That PR is 3 years old at this point, but this would probably be bundled with it, if it were to be added to the bot.

**Comment by Flame442** [comment]
After some internal discussion, it doesn't seem like this is something we are currently interested in adding to core. The use case is very limited, and it opens up some potential for abuse if it's handled incorrectly.
