### ISSUE TITLE
[Help] Tagline formatting

### ISSUE THREAD

**Issue by bobloy** [Cog-Creators/Red-DiscordBot#4669]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

Be able to use `[p]` in `[p]helpset tagline` to specify the context's prefix. Currently it will only use format on the default tagline. 

Nice to have: also the ability to reference the current command object for `command.signature` or `command.qualified_name`

Default tagline can use the context prefix: 
![image](https://user-images.githubusercontent.com/955640/101991420-8c276200-3c7a-11eb-8673-402d3a6bb89f.png)

Custom tagline can't use context prefix:
![image](https://user-images.githubusercontent.com/955640/101991456-c264e180-3c7a-11eb-9828-433d9032d36e.png)

**Comment by Jackenmen** [comment]
> Nice to have: also the ability to reference the current command object for `command.signature` or `command.qualified_name`

While there is some merit to this, I think that this would probably need a whole new command so that we can set separate taglines for cases where there isn't specific command in context (e.g. `[p]help`, `[p]help CogName`) and cases where there is (e.g. `[p]help commandname`). Perhaps even 3 commands in total if we want the tagline for the case with cog name too. If you think this is something we should look into, you can make another issue but we'll narrow this issue to just replacement of `[p]` in taglines.
