### ISSUE TITLE
Add iSort linting

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#4698]
https://black.readthedocs.io/en/stable/compatible_configs.html

The docs above provide the user with isort and black compatible settings.

we should be able to add iSort to the project in both tests and the automated linting tools.

**Comment by Jackenmen** [comment]
This needs to be put in `pyproject.toml` as a configuration for isort:
```toml
[tool.isort]
profile = "black"
line_length = 99
combine_as_imports = true
skip = [
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    "_build",
    "buck-out",
    "build",
    "dist",
    "redbot/vendored",
]
```

Along with that, we need to add appropriate isort calls to `reformat`, `stylecheck`, and `stylediff` commands in `make.bat` and `Makefile`.

While it would be nice, if the black and isort diffs were combined rather than shown separately for black and isort, it is not easily achievable with our current configuration, so that should not be blocking this.
