### ISSUE TITLE
Idea: Update Checker Feature?

### ISSUE THREAD

**Issue by SquidThePrinter** [Cog-Creators/Red-DiscordBot#47]
I had an idea: an update checker for the bot. So then every time a new release is pushed to the master branch it will notify the user during the bot's startup and inform them of the update in Console. I don't know if this is possible, but I do know that it is possible to implement GitHub API in programs, so maybe this is a possibility with that API.

**Comment by Shigbeard** [comment]
Could I make a suggestion on top of this suggestion? Perhaps, every 3-6 hours (configurable), the discordbot compares the current HEAD of the active branch, and if the local head doesn't match the remote head, assume mismatch? That's honestly the easiest way I can imagine it working (presuming its installed via Git, otherwise manually changing a variable and comparing that to the remote file may be your only viable alternative.)

I also think that in the event of a version mismatch, the "owner" as marked in the config should be given a PM to alert him/her to the version mismatch.

**Comment by Kowlin** [comment]
I'm voting of closing this issue with the introduction of `version`. From my perspective we will be unable to update the bot automatically due to the number of elements we have to update.

**Comment by irdumbs** [comment]
We should have a system like this for 3rd party repos anyway.
He's not asking to update the bot automatically Kowlin, just notify when there is an update.

**Comment by Kowlin** [comment]
Well... That can be done. Compare heads on startup. We already have a way of checking the heads.

**Comment by GhostofGoes** [comment]
The automatic git pull the bot does now is very problematic, since we have someone developing cogs, and they didn't put it in the gitignore.  This lead to the bot hanging on start, going through a loop of attempting to pull, spawning a bunch of git processes, dying, and getting respawned by the upstart script.

You should probably add some documentation relating to that for people unfamiliar with Git, or not turn on "autoupdates" by default.

**Comment by tekulvw** [comment]
Autoupdates? the bot doesn't auto update?

**Comment by GhostofGoes** [comment]
Thought I saw a commit a while back that added something with Git, but probably was another project. Took my problems to the Discord. sorry !

**Comment by Shigbeard** [comment]
Nah I could have sword red used to git pull before starting...

**Comment by irdumbs** [comment]
Red does not auto update.
This issue is about informing the user that the bot **can** be updated.

"I had an idea: an **update checker** for the bot. So then **every time a new release** is pushed to the master branch it will **notify the user** during the bot's startup and **inform them of the update** in Console"

I tossed in that notifying the user of 3rd party cog updates should also be implemented.
to expound, `!cog update` should be able to specify which cogs/repos to update as well.

**Comment by tekulvw** [comment]
The downloader cog does update the local cache of repos on start, but it does not update your bot files nor does it update any cogs in the `cogs/` folder

**Comment by irdumbs** [comment]
yes. nowhere was it said that it didn't.
users really don't need to know about downloader's cache or how it works internally.
all we want to know (in this issue) is when to `git pull` and when to `!cog update` since the bot doesn't do those by itself
