### ISSUE TITLE
Trivia Coding Bot - Answer in spoiler tags

### ISSUE THREAD

**Issue by MelSchi** [Cog-Creators/Red-DiscordBot#4700]
# Feature request
#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

Hello everyone, Sorry if the request is at the wrong place or put in the wrong way.
We are using (and very much appreciating!!) your trivia coding bot. As we are new to the topic of programing we use your bot to learn new bits and pieces every day. 
I'd like to suggest a feature which could be very useful: Could you please put the bot's answer to it's own questions in spoiler tags? So someone who is scrolling through the questions wouldn't unintentionally already read some answers.

I think this could be a very useful feature and I would very much appreciate if you could implement it.
Thanks for your attention and all the best,
Mel

**Comment by Kreusada** [comment]
I don't really see the point in this personally - why should someone not be able to read answers to questions they didn't answer? And if they did read the answer, is it a big deal? I might be catching your request wrong but users can just start their own trivia session instead of scrolling up the chats to answer existing questions.

**Comment by Drapersniper** [comment]
I don't think it's a terrible idea, and it's a very little effort request, my only concern is adding one extra step to be able to see the answer for the people currently playing the game.

**Comment by MelSchi** [comment]
> 
> 
> I don't really see the point in this personally - why should someone not be able to read answers to questions they didn't answer? And if they did read the answer, is it a big deal? I might be catching your request wrong but users can just start their own trivia session instead of scrolling up the chats to answer existing questions.

Thanks for your answer. We let the bot constantly run in an extra room, creating kind of a library of questions and answers. Maybe that explains a bit more.

**Comment by Flame442** [comment]
Currently, you can do `[p]triviaset revealanswer false` in order to stop the bot from posting answers. This could potentially be added as an extension to that setting.

**Comment by valentinsimeonov** [comment]
This Feature would help us greatly as currently we have Our Questions in JSON Format and so we Placed the Explanations before the Questions. And since, it seems, there can not be more than 1000 Characters per line, we can not place enough \n or \r in order to not see the Explantions from the begginning for many of our Questions, and also placing a lot of New Lines makes Reading Past Questions hard, as you need to Scroll Up quite a bit :)
