### ISSUE TITLE
A command to remove the configs of uninstalled cogs

### ISSUE THREAD

**Issue by npc203** [Cog-Creators/Red-DiscordBot#4724]
# Feature request

#### Select the type of feature you are requesting:
- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature
So the uninstalled cog configs are simply just bloatware that persist for eternity as junk.
A command like `[p]mydata clearbloats` (or something with a similar name). Which basically scans the uninstalled cog configs and deletes them on the user's request.

Some specifics are:
- Lists all the configs that are gonna get deleted
- It warns the owner that it'll delete those unused configs with a prompt (reaction predicate maybe).

Edit: Basically a "delete all data for uninstalled cogs" command (sorry i'm bad at explaining)

**Comment by Drapersniper** [comment]
I disagree that it should default to deleting, I would understand if upon uninstall the bot owner is asked if they want to delete. There are genuine use cases for the data persisting a cog uninstall.

EDIT: a single command that deletes all is also a bad idea in my opinion due to accidental deletion potential of it

**Comment by npc203** [comment]
Then a little more fine-tuning i guess. Like a command to list the residual configs of cogs and another in which the bot owner picks which of the configs to be deleted.

I don't want it to default delete on cog uninstall. But there could be an option to delete the config so as to cleanup space.

At this point, I'm doubting my intuition whether an eval would be enough.

**Comment by madebylydia** [comment]
-1...

Now, I am not in favor because this may alter things developers doesn't want to delete in any case...
I have that feeling it must be the developer's responsibility to handle the removal of data in his cogs, such a `delete` subcommand for setting his cog.

Talking of auto deletion on cog removal, I am completely not in favor of this. What if it's just to download the cog later? What if I miss click and oh god I deleted the most used cog of my users, what am I gonna do?? This literally shouldn't happens, even if it's a poor missclick.

Not in favor of a command to purge everything too, same thing, what if I wanted a specific cog to not be cleaned? 

Also, what if another cog need datas of a cog that has been uninstalled?

**Comment by Drapersniper** [comment]
A "list and pick" command is also not a good idea imo, the only way I consider this behaviour acceptable would be via the `[p]cog uninstall` command and absolutely no other way (unless it's designed within the cog that's deleting the data)

**Comment by ltzmax** [comment]
i wouldn't want a cog to remove everything you've setup on, and then you do `cog uninstall` what if you want to install the cog again or uninstalled by a mistake?, yea no, i don't want to auto delete everything.

**Comment by ghost** [comment]
I also don't really support auto deletion since uninstalling a cog can be done to, let's say downgrade a cog where preserving the data is key. But having a option to delete data of a cog to exempli gratia reset it would certainly be a better option than trying to force it using a eval.

**Comment by npc203** [comment]
Auto delete was never my intention. -_- , Anyways changed my mind.
Probably this would be used by a minority who have eye flinches if they see bloatware lying around or space constraints. 
Ty for all the opinions, made me realize a quick eval does a fine job rather than making a dedicated command.
 Closing this cause as Draper said, it would be wise to leave it at the discernment of the cog creators.

**Comment by Twentysix26** [comment]
I think this was actually a good suggestion so it's a shame to see it closed. 
> it would be wise to leave it at the discernment of the cog creators

Imagine if Windows told you that you cannot remove this 50gb file created by the program you've just uninstalled because $dev wants it to persist on your computer forever for whatever reason.  

The persistence of data should ultimately be a decision of the end user, especially for data that wasn't even created by core functionalities. Users will be forced to resort to hacky evals or (*gasp*) manual removal without a clean option.  
IMO the best way to go is a command that lists such configurations ("orphan" ones, so of cogs that are no longer installed) and lets you pick which one you want to delete. And maybe a prompt on `[p]cog uninstall` too for a complete uninstall.

**Comment by Jackenmen** [comment]
There's a technical limitation that doesn't allow us to *only* list orphan data - the data of a specific cog is not tied to a specific folder and a specific folder is not tied to a specific cog.

> the data of a specific cog is not tied to a specific folder

Personally, I even have such a cog (package called `redhelper`, class called `RedHelper`) that saves data to two separate folders: `RedHelper_Changelog` and `RedHelper_NewContributors`. I'm prefixing them with the class name, but it would be also possible for me to use a completely different name, say `JackCogs_SharedData` or `VirginData`.
And even without such odd cases, you still have discrepancies between even the package name and class name.

> and a specific folder is not tied to a specific cog

As for this case, more than one cog can use the same folder, the classical case of this being cogs with the same name from different authors which only differ by their cog identifier.

So, the only at all realistic way would just be listing all data folders and have the end-user figure out what's what. Then we have to deal with issues related to the fact that the data is removed at runtime, which is a problem of its own with singleton Configs or even just some cog accessing the data which the user didn't know about it.

And I think that at this point, it's just not as convincing.

**Comment by TheWyn** [comment]
As an optional parameter that defaults to not delete I'd be all for it. I'd sure make use of it when doing maintenance.

**Comment by OhCrumbs** [comment]
I suggested something along the lines of [p]cog uninstall (cog) --removedata

**Comment by OhCrumbs** [comment]
Request to reopen this
