### ISSUE TITLE
Rich logging should have a friendlier copy/paste option

### ISSUE THREAD

**Issue by TrustyJAID** [Cog-Creators/Red-DiscordBot#4868]
### What component of Red (cog, command, API) would you like to see improvements on?

Rich Logging

### Describe the enhancement you're suggesting.

Currently using Rich logging can break copy/pasting useful output for development. Specifically when working with API data I will often log the response, copy it and put it into a json formatter/validator to read easier. Right now rich will put the loggers name on the right half of the terminal including it inside the data I want to copy invalidating any json output and potentially other data formats. Rich also includes extraneous whitespace in the copied output.

**Comment by Jackenmen** [comment]
I made a mock-up of how a more copy-paste friendly logging could look ([link to code](https://gist.github.com/jack1142/b848d49f837c1bd089525d8340c5b1b9)):
![](https://cdn.discordapp.com/attachments/718148684629540905/816028448316981298/unknown.png)

The important parts of this mock-up are:
- logger name is shown *before* the log message, which allows the user to *not* select when copying the log message
- whitespace from Rich's columns (time and log level) is not present (in 2nd and following lines) when the log message is wrapped
- automatic hard-wrapping from Rich is disabled so that terminal software handles the wrapping on its own allowing the user to copy-paste the log message without the newlines getting inserted on line wraps

If someone decides to use a different design than the one I proposed here, it is important that these key points are fulfilled by it as well.
