### ISSUE TITLE
Compatibility with repl.it

### ISSUE THREAD

**Issue by inyourface34456** [Cog-Creators/Red-DiscordBot#4909]
Is it possible that you can make this compatible with repl.it?  That would be really nice because i have a hacker account on there and that is the only server i really have access to that will perform well.

**Comment by Jackenmen** [comment]
Sorry, but Red *is not* made for services like `repl.it` (and frankly, that platform is *also* not designed for hosting bots but rather to provide web servers) and it would require a very significant effort to change that (if at all feasible) due to its containerization, file system, and probably more.

Our docs contain a list of hosts that can be used to host Red (some of them are even free!) so I would suggest that you take a look at it and possibly ask more questions on [our Discord server](https://discord.gg/red):
https://docs.discord.red/en/latest/host-list.html
