### ISSUE TITLE
[Audio] play does not check if the user is in the same channel

### ISSUE THREAD

**Issue by Jan200101** [Cog-Creators/Red-DiscordBot#494]
As the title says the play command ignores where the user is or if the user is even in any voice channel

**Comment by chrislennon** [comment]
@Jan200101 I know this is an old ticket however we encountered a similar issue on our instance too. I was wondering if you were able to identify any way of replicating it?
My brief investigation turned up nothing out of the ordinary. Red reported that either:
 - User was in a voice channel that it could not join because of permissions
or
- User was not in a voice channel at all

**Comment by Tobotimus** [comment]
Is this still an issue for V2 audio?

**Comment by tekulvw** [comment]
This is fixed in V3 Audio, since V2 is feature locked I'm closing this.
