### ISSUE TITLE
[Suggestion] use default prefix to see current serverprefix

### ISSUE THREAD

**Issue by ncodex2** [Cog-Creators/Red-DiscordBot#508]
Since so many people like to use serverprefix, and set them to stupid things so they can't reset it back, possibly make the default prefix have a only command which can reset serverprefix?

**Comment by JustAB0x** [comment]
Maybe make the help command accessible with the default prefix at all time. (just in case?)

**Comment by Tobotimus** [comment]
Server prefixes are often used to prevent conflicting prefixes amongst different bots, allowing the use of the default prefix for the help command is just going to annoy all of these cases.

I'm gonna close this to say the solution is to allow mentioning the bot as a prefix with the `--mentionable` flag, since that will be unique in all circumstances, is easy to do on mobile and doesn't require remembering something.
