### ISSUE TITLE
Don`t support Java 16

### ISSUE THREAD

**Issue by DraimCiDo** [Cog-Creators/Red-DiscordBot#5084]
### What Red version are you using?

3.4.9

### What were you trying to do?

Running Bot with Java 16.

### What did you expect to happen?

I thought, bot has latest java version support

### What actually happened?

Bot don`t started

### How can we reproduce this error?

1. Install Java 16
2. Run Bot

**Comment by Drapersniper** [comment]
And we won't.

We currently support 11, and maybe in the future we will support 13.

**Comment by Drapersniper** [comment]
Note: For future reference, if you are experiencing difficulties following our install instructions which can be found here: https://docs.discord.red/en/latest/

You are free to join our support server (https://discord.gg/red) to ask your questions and so that we can help get you on your feet.

Java should not affect the whole bot run time as it is only a requirement for the Audio cog.
