### ISSUE TITLE
All local songs reported as 1 minute long

### ISSUE THREAD

**Issue by 4rm** [Cog-Creators/Red-DiscordBot#510]
When playing a song from a local playlist, the `!song` command reports every song as being 1 minute long regardless of the actual length. The song plays to completion and does not stop at 1 minute. The duration is properly reported for songs played through the `!play` command.

Example:  
![1 minute duration error](http://i.imgur.com/a2E9UxR.png)

Red is running on commit 599799 on a Raspberry Pi 3 Model B.

**Comment by Jan200101** [comment]
can confirm.

**Comment by tekulvw** [comment]
Okay this isn't really an issue. I added 60 seconds as a default for local songs because normally we find the duration of songs by the info given by youtubedl. However, local songs do not run through ytdl and therefore we do not get duration information. The default was recently added to allow the song command to work for local songs.

**Comment by 4rm** [comment]
Ah I see. Would it be possible to use something like mutagen to get the length of local tracks, possibly along with some other info?

**Comment by tekulvw** [comment]
Possible? Yes. At the top of a priority list? No. Let me get through finals, run through a few other bug fixes and I'll see what I can do.
