### ISSUE TITLE
Gives an runtime error in client.py file of the bot

### ISSUE THREAD

**Issue by Slurpcy** [Cog-Creators/Red-DiscordBot#5127]
### What Red version are you using?

3.4.10

### What were you trying to do?

just randomly using and it gave this error :
![Capture](https://user-images.githubusercontent.com/75667833/121404734-47505f80-c96d-11eb-8858-2d70160947d8.PNG)

### What did you expect to happen?

not too sure as i was using just randomly using the ie playing trivia etc

### What actually happened?

it gave an error in the terminal ``c:\users\redenv\lib\site-packages\discord\client.py:343: RuntimeWarning:        [py.warnings]
                    coroutine 'RedBase.get_context' was never awaited
                      await coro(*args, **kwargs)``

### How can we reproduce this error?

1.
2.
3.
...
i have no clue as iwas randomly using the bot

**Comment by Jackenmen** [comment]
Each occurrence of `get_context()` in this repository is awaited so whatever is causing this, it is not us.

Most likely, this is caused by some 3rd-party cog you're using. The data you provided is not enough to determine what cog is causing this so I guess you will have to manually rule out the cogs or search through the code of the cogs you're using to determine which one is the cause here.

If you need additional help, you might try asking on the #general channel on [our support server](https://discord.gg/red)
