### ISSUE TITLE
[p]set statuses should be persistant through reboots

### ISSUE THREAD

**Issue by Serpensin** [Cog-Creators/Red-DiscordBot#5157]
### What component of Red (cog, command, API) would you like to see improvements on?

command

### Describe the enhancement you're suggesting.

If you write `!sbset listening !sbhelp` to the bot he will set his status.
However, the status is deleted after a restart (of the server).
It would be an advantage if the status was retained even after a restart.

**Comment by aikaterna** [comment]
There are a few 3rd party cogs you can use for this feature, visit https://index.discord.red to search or visit our Discord server(s) to talk about it more.

**Comment by aikaterna** [comment]
There is some discussion about whether these settings should be persistent in the dev channel (AC) of the Red server. I'm leaving a link here to the relevant discussion so that whoever wants to tackle this feature in the future has some reference to ideas of implementation and/or possible issues.
https://discord.com/channels/133049272517001216/718148684629540905/857705869192724480

**Comment by Jackenmen** [comment]
Closing in favour of #3557
