### ISSUE TITLE
RASPBIAN ERROR

### ISSUE THREAD

**Issue by zarigata** [Cog-Creators/Red-DiscordBot#5166]
### What Red version are you using?

3.14.12

### What were you trying to do?

install on raspbian linux version that has  a problem to finish the install proceadure on the "CONFIGURE_OPTS=--enable-optimizations pyenv install 3.8.10 -v" part

### What did you expect to happen?

constinuaded install

### What actually happened?

pyenv: command not found

### How can we reproduce this error?

run on raspbian and follow step by step on the guide

### Anything else?

try to join the discord server, was banned for having german image but mods related as nazi....

**Comment by Jackenmen** [comment]
This issue tracker is used for reporting bugs, making feature requests, not for support.

If you need help using Red, you should ask on our support server at [discord.gg/red](https://discord.gg/red). Since I see you are banned from that server, you might also be interested in [Ban appeal process](https://forms.gle/E8STnt3Xpb1YeAuP6) but this issue tracker is definitely not the place for asking support questions.
