### ISSUE TITLE
!play not working with soundcloud URLs

### ISSUE THREAD

**Issue by w-biggs** [Cog-Creators/Red-DiscordBot#520]
Hi. I'm running a server and we can't get the play function to work for soundcloud. Our prefix is '!'.

What will happen is that we'll do '!play https://soundcloud.com/teknorapexx/getter-diss-11', and the first time we do it, it'll say 'Queued.' but never play the song. If we try to play it again, it won't say anything. Youtube works fine. Any ideas? Is there a log I should attach? Thanks. Everything is updated, we just installed this morning.

**Comment by AraHaan** [comment]
Sometimes the issue is because of an outdated ``youtube_dl`` please try to ensure all dependencies are updated by running ``pip install --upgrade [dependency here]`` for windows and for linux run ``pip3 install --upgrade [dependency here]``


After that copy and paste what is printed to console from them here for further looking.

This is because usually ``youtube_dl`` updates more than 1 time per day when something breaks.

**Comment by skeith** [comment]
@wilsonbiggs 

linux `pip3.5 install -U youtube_dl`
windows `py.exe -3.5 -m pip install -U youtube_dl`

**Comment by w-biggs** [comment]
Collecting youtube_dl
  Downloading youtube_dl-2016.12.9-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 360kB/s
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2016.11.22
    Uninstalling youtube-dl-2016.11.22:
      Successfully uninstalled youtube-dl-2016.11.22
Successfully installed youtube-dl-2016.12.9

It works now! Thanks you guys.
