### ISSUE TITLE
Start up time

### ISSUE THREAD

**Issue by vinbarney** [Cog-Creators/Red-DiscordBot#5202]
I just wanted to ask is anyone having the same issues as me?

The bot will take around 3 minutes to 5 minutes for the Lavalink to establish a connection, is it a problem from my side (Connection, Internet?) or is it something local that can be solved.

Thanks
![123123123](https://user-images.githubusercontent.com/45803108/127329727-ff65877b-37d6-4dc4-80be-2d203033041b.JPG)

**Comment by yamikaitou** [comment]
The 3-5 minutes you are seeing is the connection to Discord, not Lavalink. Lavalink appears to be connecting wtihin 5 seconds of it starting

**Comment by Flame442** [comment]
This is not something that is related to the bot, it's something probably related to the quality of either your internet connection or your computer's processing power. Due to a lack of activity, I am going to close this issue. If you have any further questions regarding this issue, please ask in the `#support` channel of the Red support server at https://discord.gg/red.
