### ISSUE TITLE
Future plans for discord.py

### ISSUE THREAD

**Issue by hkennyv** [Cog-Creators/Red-DiscordBot#5230]
Hi there,

Thank you to all the maintainers for the hard work. I just wanted to bring it to attention that it looks like development on [discord.py](https://github.com/Rapptz/discord.py) has halted (for some very good reasons outlined [here](https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1)). As I understand it, that is the core API library this project uses.

I didn't see a discussion on it yet, so I apologize if this issue is misplaced. As a user, I would love to know what that means for this project and how I could possibly help in any way.

**Comment by Twentysix26** [comment]
Hi,
it is way too early to have an official stance on the matter :)
Consider following our announcement channel in the [discord server](https://discord.gg/red). If anything major needs to be announced it will be done there.

**Comment by Tobotimus** [comment]
Hi guys, it's been a while, but I thought I'd give my 2 cents here.

I'm assuming the discussion on what Red does going forward will centre around whether to fork discord.py, or whether to go with a different fork. Here's my opinion on that.

The idea of forking discord.py came up a number of times whilst I was maintaining this project, and I was always staunchly against it. I assume it also came up after I became inactive. From my recollection, the main reasons for people wanting to fork was not necessarily due to gripes with how the library was written or maintained, but just to add ways for us to hook into internal discord.py functionality. I always viewed this as a dangerously burdensome task with not a whole lot of payoff - discord.py is a large, well-written library, and it was clear that Danny had a vision on how to maintain it. It would have been a large responsibility to fork discord.py and add our own things to it, even if a lot of that work would have been the inevitable resolving of merge conflicts when trying to bring forth changes from upstream. Now imagine how much more responsibility it would be if there was no upstream, and the entire direction of the library was up to us.

I was the first to fork the `discord.ext.commands` package (in a way, effectively "shadowing" it as `redbot.core.commands`), because we needed a lot more control over command permissions for the `permissions` cog to work effectively. The `discord.ext.commands` package was the bot framework, whilst the core `discord` package was the wrapper for the Discord API, so as a bot framework ourselves, I think it made a lot of sense for us to have forked `discord.ext.commands` and take full control of it. 

At this point, the consequences of forking discord.py haven't really changed - however, the consequences of *not* forking discord.py *have* changed. My advice is essentially this: before deciding to fork, give it a bit of time to see what happens. I understand that there are some deadlines from Discord on when some changes need to be made (new privileges/verification/slash commands), so you'll need to have the timeline in mind - set yourselves an approximate deadline for yourselves to decide on whether to fork discord.py, or go with someone else's fork. Who knows, perhaps someone Danny trusts will change their mind and become the new maintainer of discord.py. If I were still maintaining Red, I wouldn't want to rush into taking on discord.py as Cog-Creator's responsibility, even if we agreed to only maintain the library for Red's purposes, and not for the wider community.

Best of luck with everything guys ❤

**Comment by Nytelife26** [comment]
With regards to forking discord.py, I believe it could present some good opportunities. Remember that d.py was maintained by one person - we'd have good community support to make this a team effort, and many hands make light work of heavy duties.

A good approach would be to factor out a lot of Red's improvements to `discord.ext.commands` out as a framework, similar to [the Sapphire project](https://github.com/sapphiredev/framework)'s relationship to `discord.js`. From there, whether the Red community entirely forks d.py is up to the masses, but at the very least it'd be wise to create a better official framework for wider use (and our use, dogfooding is always good) and get some higher ups in a position where input is valued in design decisions for emerging forks.

That's my two cents as someone that started with d.py and Red that moved over to discord.js to help them with Sapphire, became an external contributor, and stuck around for long enough to watch it become the official discord.js framework and many staff become collaborators of discord.js itself.

I believe if the community wanted to, it could pull it off.
