### ISSUE TITLE
[Audio] Support music.youtube.com Playlists

### ISSUE THREAD

**Issue by djanatyn** [Cog-Creators/Red-DiscordBot#5347]
### What component of Red (cog, command, API) would you like to see improvements on?

Audio

### Describe the enhancement you're suggesting.

Support https://music.youtube.com/ URLs, for example:
* https://music.youtube.com/playlist?list=OLAK5uy_naZmASD9Ss3t8lqDzlYTVweJZF-dHj4gk

![nothing](https://user-images.githubusercontent.com/523628/134840468-f3842df7-3041-4f3d-85ef-6252f0c91a57.png)

**Comment by aikaterna** [comment]
Make sure your bot and your Lavalink.jar are up to date, as I received different messages when I tried your provided url:
![156125](https://user-images.githubusercontent.com/20862007/134845296-872cdc13-74c6-4dee-a349-255d3716ac97.png)


Other music.youtube.com playlists like <https://music.youtube.com/watch?v=UTHLKHL_whs&list=PL4fGSI1pDJn69On1f-8NAvX_CYlx7QyZc> and <https://music.youtube.com/playlist?list=RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs> worked just fine for me, and single songs like <https://music.youtube.com/watch?v=UTHLKHL_whs> also worked on an up to date Red, but this playlist you provided is unplayable because it requires a Music Premium account and the audio backend provides no authentication route for that. If you want to suggest support for that to the developers of that software, you can open an issue at https://github.com/sedmelluq/lavaplayer, but imo it would not be added as it wouldn't be able to be used at scale with one account.
