### ISSUE TITLE
[Mutes] Deny thread creation

### ISSUE THREAD

**Issue by flaree** [Cog-Creators/Red-DiscordBot#5371]
### What component of Red (cog, command, API) would you like to see improvements on?

Muting

### Describe the enhancement you're suggesting.

Also deny the ability to create threads. This can be easily abused as the default role made can still create threads.

**Comment by Jackenmen** [comment]
Seems reasonable.

This is blocked until we move to a library with support for the new perms.

**Comment by Jackenmen** [comment]
I've been told this can still be done by constructing `discord.Permissions`/`discord.PermissionOverwrite` object with raw permission value. It's therefore up for grabs.
To make this maintainable, please document a name of each of the used bits to avoid the confusion *and* add a DEP-WARN comment so that this can get replaced with a simpler solution once we update d.py.

**Comment by flaree** [comment]
Seems to be in dev now since the move, closing.
