### ISSUE TITLE
[Audio] Trying to play too long track does not autodisconnect bot

### ISSUE THREAD

**Issue by walliski** [Cog-Creators/Red-DiscordBot#5413]
### What Red version are you using?

3.4.14

### Cog name

Audio

### Command name

play

### What did you expect to happen?

When trying to queue a song that is longer than the set limit, and the bot is set to disconnect when playing is done, I expect the bot to disconnect, or not even connect to a voice channel if the song is too long.

### What actually happened?

When you try to play a song that is too long, the bot joins the voice channel, says the song is not valid, and stays in the channel.

### How can we reproduce this error?

1. Set autodisconnect when playing is done
2. Set limit for song length
3. Queue a song that is too long

**Comment by aikaterna** [comment]
We can't load tracks or get any information about them until the bot has connected to the voice channel, therefore there's no way to check track length before connecting. Since nothing ever started playing, there is no queue end event firing off. I don't feel like this needs to be added either - there would be a lot of conditional checking and this would possibly be messy to try to catch this condition.
