### ISSUE TITLE
[Core]`[p]Embedset command <command>` should include subcommands.

### ISSUE THREAD

**Issue by the-krak3n** [Cog-Creators/Red-DiscordBot#5454]
### What component of Red (cog, command, API) would you like to see improvements on?

embedset

### Describe the enhancement you're suggesting.

The `[p]embedset command <command>` toggles it on/off for only the mentioned command but I think it will be more convenient to include the subcommands as well because if there are too many subcommands we need to toggle it for every subcommand the command has.

**Comment by benno1237** [comment]
Not a huge fan of this tbh. Extra setting for each command? Thats a hell lot of setup and config usage.

**Comment by Jackenmen** [comment]
@the-krak3n This has been discussed before in the PR that introduced this feature: #4049
I suggest reading the discussion there and if you don't agree with the reasoning there, you should make a counter argument.

@benno1237 I don't know what you are talking about? Can you elaborate?

**Comment by benno1237** [comment]
Ignore me. I confused a few commands here. Sorry for that.

**Comment by Flame442** [comment]
There has been no further discussion regarding how this solution compares to the current solution, given the existing discussion as reference. I am going to close this issue since it is stale, but anyone may feel free to reopen it with a counter argument to the existing discussion for further consideration.
