### ISSUE TITLE
Bug and suggestions

### ISSUE THREAD

**Issue by LifeSquad** [Cog-Creators/Red-DiscordBot#557]
bug: game is reset if status isnt online/status is reset to online when a game status is placed

suggestion #1: add a command that shuts red down (not pshutdown, that turns the whole bot off) but like a command so if you're somewhere where you can't turn the bot off/on, you can turn it off the back on (while launching the bot with startRedLoop)

suggestion #2: Make mod log messages in embeds. (1 giant embed)

suggestion #3: add the ability to ban users using the user id, so they don't have to be in the server to be banned. (time when it can be used is when you know someone banned made an alt account and may be able to join on a different device with a different IP Address)

*Edit: Rewording and syntax fixing --Kowlin*

**Comment by Kowlin** [comment]
The bug isn't a bug, We keep the status when updating the game, and the other way around. This is a outdated bot.

For the suggestions:
1. If the user fully wants to stop the bot. Then the user can use ``startRed.bat`` instead of ``startRedLoop.bat``. These things do what they say on the cover. They both run the bot, but one restarts the bot when it goes down. The user can chose on what he wants.
2. This won't work. Like everything in Discord, Embeds have a cap on how much stuff we can throw into one.
3. We cannot ban users without "knowing" them. This is a limitation on Discord's end.
