### ISSUE TITLE
[Audio] Discourage users from using [p]llset to fix unrelated issues

### ISSUE THREAD

**Issue by Flame442** [Cog-Creators/Red-DiscordBot#5571]
### What component of Red (cog, command, API) would you like to see improvements on?

Audio

### Describe the enhancement you're suggesting.

Currently, users are directing themselves towards `[p]llset` in order to fix issues with lavalink that should be fixed in other ways. This causes slower resolution times for support staff who need to start off by getting these changes reverted before the actual problem can be diagnosed and fixed.

`[p]llset`'s docstrings do not make it abundantly clear that the subcommands are intended for advanced usage only, not for normal setup of the bot. These should be modified to discourage changing the default values unless the user is absolutely sure they know what they are doing. The command may also need to be hidden, however this is an unideal solution as it makes it less obvious for users who would use these commands appropriately.

The "**Unable to play tracks** Connection to lavalink has not yet been established." response when lavalink has not finished starting up does not make it clear that the bot *is attempting to start and connect to* lavalink when lavalink is managed internally without looking at console. Thus, users think the connection was not established not because they need to *wait* for it to be established, but because they haven't properly set up the connection. This causes many to get lost in `[p]llset` trying to fix the issue. When lavalink is managed internally, this message should be expanded to make it clear that the bot is trying to start the server and that console will have information about its progress. When lavalink is managed externally, this message should be expanded to remind the user that they need to start up lavalink for the bot to connect to.

**Comment by TwinDragon** [comment]
Some discussion I recall about this would possibly to hide `llset` and its subcommands from view, so that other users don't get the idea of messing with settings they really shouldn't be messing with in 99% of use-cases for Lavalink.

I honestly think this is probably the route that probably would work. A case of "out of sight, out of mind" deal.

Though, some verbiage about internally-managed instances of Lavalink could probably be better that the bot is either starting the instance, or attempting to start it. (as sometimes there could be multiple instances running causing the `Port in use` error)
