### ISSUE TITLE
Config no longer converts non standard objects

### ISSUE THREAD

**Issue by flaree** [Cog-Creators/Red-DiscordBot#5585]
### What Red version are you using?

3.5.0.dev1

### What were you trying to do?

Pull a registered default (Counter) from config and add it to a current counter, then set it back.

### What did you expect to happen?

Correctly cast the the object back to Counter, it only cast it back to dict.

### What actually happened?

The object was cast by a dict, and thus errored when trying to add to a counter.

![image](https://user-images.githubusercontent.com/31554168/155208404-bc79fb1a-c0b8-4a8f-93eb-a7572f292e35.png)

### How can we reproduce this error?

1. Load commandstats on current dev version.
2. Run any commandstats command or just watch the logs as it updates on an interval.

### Anything else?

@jack1142 

https://canary.discord.com/channels/133049272517001216/718148684629540905/945755778353102929 (discussion in #AC)

**Comment by Jackenmen** [comment]
This is caused by the recent change to Config:
https://github.com/Cog-Creators/Red-DiscordBot/commit/b0ab6186ef20ef16d97d9a2f8771417b08ea27f3

As it turns out, setting a default for a key to a `dict` subclass makes Config return that subclass when you access that key.

I'm not entirely sure whether we should just swallow the pill on this one and keep this change (and remember to properly document it) *or* if we should revert this change entirely (and be sure to add a regression test).

I'm leaning towards reverting this as even though it's an unintended consequence of how `Group.nested_update()` is implemented, this usage makes some sense.

@Flame442 you might have some opinion on this since you were reviewing this one.

**Comment by Jackenmen** [comment]
There's actually a third option... We could special-case dict and its subclasses (they're already treated special in many places anyway) and only keep the behavior introduced by https://github.com/Cog-Creators/Red-DiscordBot/commit/b0ab6186ef20ef16d97d9a2f8771417b08ea27f3 for all other types where setting non-serializable default had to just be someone setting this without knowing what issues it causes since it's guaranteed to result in inconsistent behavior.
