### ISSUE TITLE
[Audio] Save current track progress on async cog_unload

### ISSUE THREAD

**Issue by Zephyrkul** [Cog-Creators/Red-DiscordBot#5650]
### Type of feature request

Other

### Description of the feature you're suggesting

As discussed in #advanced-coding in the Red server.

With discord.py 2.0's new asynchronous cog_unload, it should now be possible for Audio to save current track progress in cog_unload for resuming when it starts up again.
For reference, current behavior only resumes from the first track in the queue rather than the playing track.

**Comment by Flame442** [comment]
Audio currently restores the current track and queue state. Because restarts should be fairly infrequent in Red, the added complexity needed to restore the track *position* for all the bot's players is not worth the comparatively small benefit for users. This is not something we are currently interested in implementing.

**Comment by Zephyrkul** [comment]
> Audio currently restores the current track and queue state.

This is untrue. It only saves the queue; it does not save the current track.
