### ISSUE TITLE
General server population unable to use custom commands

### ISSUE THREAD

**Issue by beziercurve** [Cog-Creators/Red-DiscordBot#576]
I thought there was an issue with permissions but that doesn't seem like the case. I've added several custom commands to Red but myself (owner) and mods are the only users able to use commands at all. Any ideas? Thanks!

**Comment by Kowlin** [comment]
Hi, sorry for the somewhat late reply. Did you set a white-/blacklist on the bot? Having a whitelist set means that users aren't able to use any commands on the bot.

**Comment by beziercurve** [comment]
Ah, hmm, no not that I know of. I used the whitelist to test if that was what I was missing for letting a user access bot commands, but the whitelist seems to let a user use any command including admin commands. The bot is entirely default, no cogs or anything, just a couple of custom commands I'm using to test with.

**Comment by Kowlin** [comment]
Since you've set a whitelist I recommand you use ``whitelist clear`` and try again. As for the admin commands. Only the users with the Admin role can run admin commands. Or have the equivalent permission to run the command,
as example: A user that can kick from Discord can use the kick command, regardless of having the Admin role.

**Comment by beziercurve** [comment]
`Whitelist clear` fixed it - thank you!
