### ISSUE TITLE
[JSON Schema/Index] Add a new key for cog's info.json to indicate if ready for d.py 2.0/Red 3.5

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#5836]
### Type of feature request

API functionality, Other

### Description of the feature you're suggesting

The suggestion here implies the cogs `info.json` and Red's index.

The idea is to add a new key called for example `is_dpy_2_ready` to indicate that the bot has been updated for discord.py 2.0.
The values takes a bool, each of them representing the following:

`true`: The cog is ready for being usable after Red upgrades discord.py to `2.0`.
`false`: The cog is NOT ready for being usable with Red after it upgrades to discord.py `2.0`.
Not a boolean or not present: The status is unknown, cog should work but breakage should be expected by users.
`str`: The cog is NOT ready for being usable with Red and the contained value should be shown to users.

This new key would be available in the Red's Index.
If possible, this change should be ported too to the Twentysix's `index` cog to help users.

When installing (or even better, when loading) a cog, Red could indicate that the cog is not/may not be ready for discord.py 2.0 if the cog fails to load AND/OR the value of the key is `False` or not specified.

### Anything else?

If accepted, this suggestion should be implemented for when Red will upgrade discord.py, else there's no real point in this suggestion after then.

I am willing to create a PR for this issue.
If anyone else is interested in taking this issue, however, feel free to leave a comment.

**Comment by Dav-Git** [comment]
Why can't we use the already existing min and max bot version keys for this?

Since those aren't currently enforced we might want to add a [p]load implementation that respects the values of these keys.

I don't think we should be adding more attributes to the info.json if we can already represent the desired functionality with existing attributes.

**Comment by Vexed01** [comment]
If the approach to use existing keys is taken, I think there should be standardisation regarding how to set a max version. Should 3.5 compatibility be `3.5.99`, `3.6.0.dev0`, or maybe something like just `3.5` allowing for all 3.5 releases. I think this standadisation is especially important if this key will be incorperated with an automated 3.5 (and 3.6 etc?) compatibility flag.

**Comment by madebylydia** [comment]
> Why can't we use the already existing min and max bot version keys for this?

As of today, we can. I just think their use in this context is poor.
These keys are, in my sense, more interesting to use when it is about Red's APIs itself only (Config, Bank, and so on). The difference here being that it's about Red's dependency, and not its APIs in any sense.
This key stay vague, and I think that we need more clearance here.
Looking back of when some users asked about "Have you guys heard of slash commands?", I expect quite the same and some of the same kind to actually come and say "Do you guys know if X cog support d.py? It doesn't damn load!", this is where this key can be very useful IMO.

Also, I'm personally making this suggestion most especially for Red's Index as to indicate to users which cogs are ready and which are not.

> Since those aren't currently enforced we might want to add a [p]load implementation that respects the values of these keys.

They strongly are, but in `[p]cog install/update/...`. I guess that's what you meant? :p

> If the approach to use existing keys is taken, I think there should be standardisation regarding how to set a max version. 

Aren't they are already? (By the look of https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/schema/red_cog.schema.json#L30-L39)

--------

On another note, @jack1142 suggested adding a command to the downloader cog to "check all of their installed cogs to know if they already have an update that makes them work with 3.5."[^1].
I think it's important to add it here, but this might require a different issue to be opened.

[^1]: https://discord.com/channels/133049272517001216/718148684629540905/946374021329584148

**Comment by Flame442** [comment]
> These keys are, in my sense, more interesting to use when it is about Red's APIs itself only (Config, Bank, and so on). The difference here being that it's about Red's dependency, and not its APIs in any sense.

Then rather than a key *specific* to this update that would only be used one time, would you consider a `min/max_dpy_version` key something to satisfy this request?

I do agree with the idea to pass a partial update number to state "all micro updates of this version" (like passing `3.5`). While right now you *can* do `3.6.0.dev0` for the same behavior (since the first patch is almost always something trivial like the version bump) it is somewhat bad UX for a cog dev, and hard to *know* that's what to do. If this key (and the other `min/max`s) supported that functionality, I think that would be an OK solution to this problem. 

> On another note, jack suggested adding a command to the downloader cog to "check all of their installed cogs to know if they already have an update that makes them work with 3.5."

If the above key(s) are used, I'd be more inclined to agree with the previously discussed solution of unloading all of a user's cogs the first time they launch 3.5 (through the same system that `--no-cogs` uses, which doesn't remove them from the list of previously loaded cogs?), and messaging owners that they should *probably* run `[p]cog update` and restart the bot. That way they would get the same notice that some cogs do not support the new bot version without adding a new command which is *also* one time use for 3.5.

The other option I would agree with more is to enforce `info.json` versions in the loading code, but I personally don't like that option since it makes it borderline impossible to override a cog creator's claimed `info.json` versions in cases where you *know* it works (or works well enough) on a version not covered by the guarantees.
