### ISSUE TITLE
Support for dpy 2.0 stable

### ISSUE THREAD

**Issue by AdamTuraj** [Cog-Creators/Red-DiscordBot#5849]
### Type of feature request

API functionality

### Description of the feature you're suggesting

Hello, I am working on preparing my bot for Red 3.5 but have run into many unsupported methods due to discord.py being an old alpha version. It would be much appreciated if this can be done ASAP.

### Anything else?

I tried implementing this myself and it seems there is only 1 issue. I found the issue was something added to the error handler recently. Other then that it loaded fine though I did not test any commands or other Red features.

**Comment by yamikaitou** [comment]
#5709 is where we are tracking the update to dpy2

**Comment by Flame442** [comment]
Red is an open source project, and as a result all work that goes in to Red is done by people volunteering their time. Since we do not want to force people to work for free, changes get made when people have time and updates are released when they are ready.

3.5 will contain a version bump to some version of dpy 2.0. The progress towards 3.5's completion can be tracked with the 3.5.0 milestone. The PR Yami brought up is on that milestone, and will likely be included in 3.5. No timeline will be provided for when 3.5 will come out, so the milestone is the best place to look to see how much *progress* is being made to get to that point. If there are any unaddressed issues in that milestone you would like to contribute towards, that may make things go faster.

If you have any further questions about the development process of Red, I urge you to ask in our [support server](https://discord.gg/red), rather than making an issue.
