### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by jsargent8789** [Cog-Creators/Red-DiscordBot#5917]
No audio in discord channel when using command play

**Comment by leetfin** [comment]
Traceback?

**Comment by Flame442** [comment]
This issue was not made with our bug report template, however it appears to be intended to be bug report. Without the information in the template (reproduction steps, version information, etc), this is likely better asked as a support question instead.

Support questions can be asked in the [Red discord server](https://discord.gg/red), but I'll provide some basic troubleshooting steps to try and get you started. Any followup questions should be asked in the support server, unless this is a reproducible bug and you can provide clear information about what is causing it.

---

**If the bot's speaking light is active, but there is no sound, try these:**
```md
1. Is the bot's user volume turned up? (right click on the bot in discord, see the slider)
2. Is the bot muted or deafened? Are you deafened? Are you deaf?
3. Check Discord audio device settings and volume (cog icon next to your username in the bottom left, click "Voice and Video")
4. Try dragging and dropping the bot back to the voice channel.
5. Check system audio device settings and volume
6. Ask another member to come into the voice channel to confirm that it's not just you
```

**If the track progress is stuck on 00:00 when you run `[p]now`:**
```md
1. Try to run [p]disconnect and replay the song
2. Try to reload the audio cog with [p]audioset restart
```

If all else fails, join the [Red discord server](https://discord.gg/red) and ask for help in the `#support` channel there.
