### ISSUE TITLE
Error on Audio and cogs

### ISSUE THREAD

**Issue by zarigata** [Cog-Creators/Red-DiscordBot#6175]
### What Red version are you using?

3.4.5

### Cog name

CogManagerUI

### Command name

!audio

### What did you expect to happen?

audio working

### What actually happened?

it gave me a error with 
Failed to load the following package: audio.
Check your console or logs for details.

and the error on the console

### How can we reproduce this error?

1.open new bot 
2.try to install any cog
3try to run audio
4. error recived
...

### Anything else?

           ERROR    [red] Package loading failed
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\discord\hrbot\Lib\site-packages\redbot\core\core_commands.py:188 in _load                                  │
│ >  188                 await bot.load_extension(spec)                                                               │
│ C:\Users\discord\hrbot\Lib\site-packages\redbot\core\bot.py:1686 in load_extension                                  │
│ > 1686             await lib.setup(self)                                                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: object NoneType can't be used in 'await' expression

**Comment by Flame442** [comment]
I assume you did not actually check your bot version, and just copied the default for the version slot, but if you *are* on 3.4.5 then your instance is very out of date, and you need to update the bot. Otherwise, you likely have a 3rd party `audio` cog that is overriding attempts to load the core version, leading to that error. If you need further support, please seek help in the [Red support server](https://discord.gg/red) where it is easier to give realtime support.

**Comment by zarigata** [comment]
@Flame442  i cant join the discord server because i was falsely flag as z4zi because i have a skull as a profile picture as the same as in git hub, I've used the latest version of the red bot and followed the steps on the website, i just wanted some help
