### ISSUE TITLE
Update DM instructions not always doable

### ISSUE THREAD

**Issue by Vexed01** [Cog-Creators/Red-DiscordBot#6201]
### What component of Red (cog, command, API) would you like to see improvements on?

Core / events

### Describe the enhancement you're suggesting.

The current instructions assume all Linux users can open Terminal, though many Red users will be hosting on something without a GUI like Ubuntu Server. It would probably be a good idea to add something about running the command over a SSH connection if a window of Terminal isn't appropriate.

### Anything else?

https://github.com/Cog-Creators/Red-DiscordBot/blob/8ee3ac9352724c64c76763b03a1e74cc427c4235/redbot/core/_events.py#L119-L130

**Comment by Dav-Git** [comment]
While you are technically correct, I think this is a mental transfer we can expect people to make. If they managed to install red, they will probably manage to figure out where they need to run the command.

For the sake of keeping the message quick and easy to read I would be in favor of leaving it as is.

**Comment by Flame442** [comment]
I would say the disclaimer provided in the earlier section is enough to make it clear that it isn't going to be perfectly accurate. Since we have no way to know if they are running it on a machine they need to SSH into or not, I don't think it makes sense to make that message even more wordy.

https://github.com/Cog-Creators/Red-DiscordBot/blob/8ee3ac9352724c64c76763b03a1e74cc427c4235/redbot/core/_events.py#L64-L70
