### ISSUE TITLE
Audio detected multiple continuous errors during playback

### ISSUE THREAD

**Issue by Micru0** [Cog-Creators/Red-DiscordBot#6220]
### What Red version are you using?

3.5.3

### Cog name

Admin

### Command name

!play

### What did you expect to happen?

Firstly, I updated the bot and the audio errors occurred. 

Then it said there was an update so I updated. Lastly, I could not use !cog update because nothing was happening then someone on this forum suggested downloader so I did that and it worked but gave me the msg "could not detect any cogs". 

The bot sometimes stays on but other times turns off instantly.

### What actually happened?

Keeps turning off with this error. 

     INFO     [red.Audio.WS.LLNode] Lavalink WS connecting to ws://localhost:2333 with headers {'Authorization': 'youshallnotpass', 'User-Id': '931503123317547061', 'Num-Shards': '1', 'Client-Name': 'Red-Lavalink/0.11.0', 'Resume-Key': 'Red-Core-Audio-931503123317547061-Babu'}
[22:36:58] INFO     [red.Audio.WS.LLNode] Lavalink WS connected to ws://localhost:2333
[22:37:11] WARNING  [red.cogs.Audio.cog.Events.lavalink] Audio detected multiple continuous errors during playback - terminating the player for guild: 320005318819971084.

### How can we reproduce this error?

1.!play
2.Audio issues detected 
3.
...

**Comment by aikaterna** [comment]
First of all, I assume you mean the play command from the Audio cog and not Admin. Secondly we'd need your spring.log file from your Audio data directory to confirm, but some songs won't play currently and this will be fixed with a new Red release which you should see in the future sometime when we get to it.

Edit: if you have more trouble, join the support server at discord.gg/red so that we can help.
