### ISSUE TITLE
Support uploading banners

### ISSUE THREAD

**Issue by yamikaitou** [Cog-Creators/Red-DiscordBot#6321]
### Type of feature request

Command

### Description of the feature you're suggesting

Add a command to `set bot` that allows modifying the banner

**Comment by Vixxel** [comment]
I definitely think this is also a good idea to have. Perhaps we can get more specific and instead of just "set bot" we can include "set banner" or "set bot banner" and a link that would allow the banner to be set and published. 

I also think we should have one for an avatar too, there are probably plugins out there for this but having it as an actual feature of the bot might be useful for people not wanting to install plugins.

**Comment by aikaterna** [comment]
We already have set bot avatar as a command in core.
