### ISSUE TITLE
(Commands)Renaming Commands

### ISSUE THREAD

**Issue by HorizonTM** [Cog-Creators/Red-DiscordBot#638]
Maybe try to make it so that people can rename the commands of ones that are already existing or is it a limitation?

**Comment by Jan200101** [comment]
It is already possible but not without editing code, but doing so will make updating a pain

**Comment by skeith** [comment]
Renaming is one thing, but adding alias is a thing that is already possible. If you would not mind about not being able to totally erase the old name, alias module is there for you

**Comment by Twentysix26** [comment]
Aliases are already a thing. Renaming at runtime is possible but sounds very messy in certain situations.
Example:
* cog with "!test" command gets loaded
* "!test" command is renamed to "!test2"
* a different cog with a "!test" command gets loaded. It loads successfully because the other command is now called "!test2", avoiding the conflict
* Red is restarted
* These two cogs now conflict and one fails to load because all cogs get loaded at once and the rename is done after that  

Not to mention that the initial cog loading is currently unordered.
I'm sure it's possible with enough rework but I don't think it's worth the hassle. It might be a valid 3rd party cog idea.
