### ISSUE TITLE
Audio cog no longer functions on any YT videos

### ISSUE THREAD

**Issue by CorneliusCornbread** [Cog-Creators/Red-DiscordBot#6399]
### What Red version are you using?

3.5.9

### Cog name

Audio

### Command name

play

### What did you expect to happen?

Bot joins channel and audio begins playing.

### What actually happened?

Seems to be related to the last issue in #4505 but now this applies to all songs. Songs that used to work as of a few days ago no longer work at all.

### How can we reproduce this error?

1. Play a youtube song
2. Error

### Anything else?

I've tried resetting my venv and updating my cogs from there but that didn't resolve the problem. I also tried to reinstall the Lavalink jar by deleting it but that also didn't result in any change in behaviour. I've attached the relevant log file for lavalink

[spring.log](https://github.com/user-attachments/files/16151327/spring.log)

**Comment by japandotorg** [comment]
If you're experiencing playback issues with Audio and YouTube or Spotify links, the issue is known about and some fixes are in progress. In the meantime while we're waiting on a Red update, you can play music from other sources and links:

SoundCloud
Bandcamp
Vimeo
Twitch streams
[HTTP URLs](https://radio-browser.info/) (Toggle `[p]audioset restrict` to allow non-commercial links)
[Local tracks](https://docs.discord.red/en/stable/cog_guides/audio.html#local-tracks)

Subscribe to [#red-news](https://discord.com/channels/133049272517001216/133080797660971008) (in the [official redbot server](https://discord.gg/red)) if you wish to be alerted when there is a new Red update.
