### ISSUE TITLE
Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by CRASNY** [Cog-Creators/Red-DiscordBot#641]
First:
```
C:\WINDOWS\system32>pip3 freeze
beautifulsoup4==4.5.3

C:\WINDOWS\system32>python -V
Python 3.5.3
```

Since this afternoon, quite randomly, my Red has been throwing errors in the console. The only recent changes I've made are adding a few trivia lists, and the only extra cogs I've got installed is one dealing with RSS feeds. Both the RSS and trivia cogs have been working perfectly fine.

http://pastebin.com/V4b84JrK
http://pastebin.com/ujmihMAD

Above are the errors I've been getting. I'm very clueless as to what could be causing these. Any ideas?

**Comment by Twentysix26** [comment]
Most likely connection issues. Anyway, update your bot if you want it to auto restart reliably.

**Comment by CRASNY** [comment]
Thank you for the fast reply and thanks for creating Red. It is auto-restarting reliably as is, running the latest version, I was just curious about this as it has been crashing every 10-15 minutes.

By connection issues, are you referring to something on the end of the machine that's running my Red? The connection has been fine all day, but I'll give it some time to see if it heals naturally. Thanks again.

**Comment by Twentysix26** [comment]
Probably the connection between the machine and Discord. I'd suggest to wait it out

**Comment by abuneri** [comment]
I'm having this problem as well, seems to only happen on a cog I made, which is also for RSS feeds. Could this possibly be a user error? Here's a code snippet of what I'm doing:

```
async def _rss(self):
    rss_delay = 30

    while self == self.bot.get_cog("RSSFeed"):
	#do stuff here...
        await asyncio.sleep(rss_delay)
    
def setup(bot):
    check_filesystem()
    rss_obj = RSSFeed(bot)
    bot.add_cog(rss_obj)
    bot.loop.create_task(rss_obj._rss())
```

When this issue started, I originally was getting the event loop from asyncio directly with:
```
loop = asyncio.get_event_loop()
loop.create_task(rss_obj._rss())
```
But it still persists using the bot objects event loops (which may be using the `set_event_loop()` or `new_event_loop()` method instead of getting the event loop for the current context.

Danny has commented on issues in discord.py saying it's most likely a user error, it would be nice to not have to rely on restart, but might as well just do that for now...

**Comment by Twentysix26** [comment]
@sedruk That's most likely your code and not really related to OP's issue.

**Comment by abuneri** [comment]
yeah, that is what I expect, thanks!
