### ISSUE TITLE
Implement warning by user ID.

### ISSUE THREAD

**Issue by RdrSeraphim** [Cog-Creators/Red-DiscordBot#6445]
### What component of Red (cog, command, API) would you like to see improvements on?

warnings

### Describe the enhancement you're suggesting.

It seems that this was once behavior for the cog a long while ago, but I would like to propose allowing warns by user ID. It would be useful to warn IDs of users who, say, violated a rule but left before any warning could be given.

### Anything else?

I'm not sure how this would intersect with warn actions, I'm not sure how the cog would perform these on absent users. I would also be willing to try and take this enhancement on if that would be preferable. My current line of thought would be to replicate the member param validation from `[p]warnings` and ignore DMing if the member isn't present.

**Comment by Needless2Say** [comment]
Hi, can I take this?

**Comment by aikaterna** [comment]
We don't assign non-members to issues. Feel free to work on it if you wish.

**Comment by Flame442** [comment]
At least as far back as the start of V3, `warnings` has always taken a `Member` as the argument ([ref](https://github.com/Cog-Creators/Red-DiscordBot/commit/c1ac78eea4f036c377f70799112cd544e3a14ee5#diff-1fa0574b7404468882355fe1f64fa85f3efec457da84180904112ddb54f41d17R222)). Perhaps you are thinking of `[p]ban` or similar commands?

As you pointed out, this seems a little hard to address given the nature of a warnings based cog. `warnings` allows actions to run any arbitrary command on the user, and cannot guarantee that the command will succeed if given an ID of a user who has left the server. It would make sense to allow a `[p]warn` that would give enough points to execute the `[p]ban` command to be used on a user who has left the server, since a user who is at that tier should be banned regardless of if they try to rejoin the server, and the ban command is able to accept IDs of members not in the server. However, something like `[p]timeout` which *requires* the user to be in the server would need to wait for them to rejoin (resulting in the timeout length not starting until after they rejoined, for better or for worse). There is no easy way for `warnings` to tell the difference between these cases and handle them individually. The only option that could work is always waiting until the user rejoins, but that requires the bot to be online when the user joins for them to be punished.

I am not certain if that added complexity is worth the effort for this edge case. If a disruptive user is leaving before a moderator is able to take action, it may often make sense to consider them a troll and bypass the server's standard `warnings` track.

**Comment by Ascensionn** [comment]
> I am not certain if that added complexity is worth the effort for this edge case. If a disruptive user is leaving before a moderator is able to take action, it may often make sense to consider them a troll and bypass the server's standard `warnings` track.

So yes, so in that case I can modify the [p]warn command to ban the user by their ID if they have already left the server. I also believe it is fair to assume they are a troll and should not be allowed back in the server.
