### ISSUE TITLE
Allow custom select options in SimpleMenu

### ISSUE THREAD

**Issue by barr-israel** [Cog-Creators/Red-DiscordBot#6455]
### Type of feature request

API functionality

### Description of the feature you're suggesting

SimpleMenu should allow custom names for the pages instead of the hardcoded "Page X".
The most straight forward solution I can see is to take an optional list of names when creating the menu and if its given, use it instead of generating the "Page X" list.
My cog currently "hacks" the existing behavior using 
```python
menu.select_options = [discord.SelectOption(label=n, value=num) for num, (n,_) in enumerate(menu_items)]
menu.select_menu = menu._get_select_menu()
menu.add_item(menu.select_menu)
```
(menu_items is a list of tuples of (name,content) in this case)
### Anything else?
I can write a pull request myself if needed.

**Comment by TrustyJAID** [comment]
SimpleMenu is meant to be a quick easy way to create a menu by providing the list of pages. It's an evolution on Red's original menu system adding some quality of life with the select menu picker to jump to specific pages. Generally I would recommend making your own view and menu if you want to customize the select pages. Alternatively since SimpleMenu is a view you can just write your own select menu to add to it with the `add_item` method. 

The only complex part of SimpleMenu is how it handles when there's more than 25 options in your list.

In order to support this I would suggest moving `self.select_menu = self._get_select_menu()` into the `start` and `start_dm` methods so that the select options can be modified using `menu.select_options = <list of SelectOption>` without needing to call the internal method  `_get_select_menu`.
