### ISSUE TITLE
Nothing found and video requiring login for audio

### ISSUE THREAD

**Issue by MadHatterHoff** [Cog-Creators/Red-DiscordBot#6456]
### What Red version are you using?

3.4.5

### Cog name

Audio

### Command name

play

### What did you expect to happen?

Audio to successfully play in the voice channel.

### What actually happened?

Bot joined the channel, but threw a "Nothing Found" message containing "This video requires login"

### How can we reproduce this error?

1. Create new discord bot with Red
2. Provide the credentials need and add YouTube and spotify APi config.
3. Attempt to play youtube or spotify music

### Anything else?

this is my first time trying to make a music bot and have been following multiple tutorials, though I am not sure what the issue could be here

**Comment by aikaterna** [comment]
Your ip address/host ASN has been banned by youtube and you'll need to find one that still works, or manage the audio backend yourself and try other methods that the Lavalink project has available for the version of Lavalink we currently use, which is v3. We don't provide direct help in getting around this block, as there isn't anything we can do since it's related to your host and how youtube is choosing to protect their service. Other services like bandcamp, soundcloud, icecast/shoutcast streams or local file playback will still work for you, this issue is only in regards to youtube playback.
edit: And in regard to Spotify playback, those songs are never played directly, and are looked up on youtube instead, which will also return this error.
