### ISSUE TITLE
[Mod] Should kick/ban/softban/mute respect hierarchy?

### ISSUE THREAD

**Issue by Twentysix26** [Cog-Creators/Red-DiscordBot#652]
And by that I mean checking `author.top_role.position > user.top_role.position`  
Perhaps optionally? Thoughts on the matter?

**Comment by Kowlin** [comment]
I think a optional yes with defaulting to on. Due the fact that this already is in Discord's own hierarchy structure.

**Comment by flapjax** [comment]
I vote **optional** because of one weird reason: top_role determines name color. There are some cases where you might want to give someone (e.g. a mod) a special name color, and thus a custom top_role, without granting them an exclusive ability to use mod commands on people that are supposed to be equivalent to them but are now lower on the heirarchy. This is one of my favorite features of Red at the moment. I can do all admin and mod functions via the bot, and let everyone have custom name colors, without worrying too much about my role heirarchy.

**Comment by palmtree5** [comment]
I would agree with optional

**Comment by Jan200101** [comment]
I also agree with making it optional

**Comment by Sanduhr32** [comment]
Kick/Ban/Softban respects it 'cause role hierarchy. Mute shouldnt respect that, if the Redbot role is lower than the role of the user/role, you cant edit the effective-permissions (role hierarchy)

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/7c192b366858bb43f1e199efe28863b0ed13be27
