### ISSUE TITLE
Error: "Sharding required.."

### ISSUE THREAD

**Issue by ncodex2** [Cog-Creators/Red-DiscordBot#713]
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4011, reason = Sharding required..

**Comment by Zephyrkul** [comment]
How many servers is your bot connected to?

**Comment by ncodex2** [comment]
Around 2800.

**Comment by Jan200101** [comment]
are you sure ?
you can do
`[p]debug len(bot.servers)`
to find the real number

**Comment by ncodex2** [comment]
Yes, i am sure, my bot is quite large.

**Comment by Zephyrkul** [comment]
Red only supports connecting up to 2500 servers - any more requires [sharding](https://discordapp.com/developers/docs/topics/gateway#sharding), which Red does not support out of the box. This is a requirement of Discord's API.

**Comment by Kowlin** [comment]
Like Zephyr said, bots that have over 2500 servers require sharding. Out of the box we do not support sharding due the number of critical changes we would have to make to Red. 

For Red to reliable support sharding we would need to move away from our current method of saving everything into Json's (What works fine for the majority of cogs and add-ons) into a structured or non-structured database (#517)

We would also have to specifically ask for the number of shards, and thread them into their own red processes. (Not sure on that) And that logic currently doesn't exist in Red. There are probably more challenges for Red to support sharding down the line. 

Why have we not added support for sharding when it was announced? Because we simply don't have a need for it, the majority of users who use Red (A good 99.5%) don't require it. Building the back-end for sharding is by it self a huge task, a task that would only apply for 0.5% of users. And that isn't a good method for spending our time in my opinion.

There however is some good news in this bundle of information; the rewrite of Discord.py will support sharding out of the box. (https://github.com/Rapptz/discord.py/projects/1) And this should make it easier for you to have support for sharding. Does this mean that it will work once the Discord.py rework is out? Absolutely not, we would have to port over Red first.

What could you do for now? You can try to get the bot running in multiple shards and hard lock it down to <2501 servers until we either support sharding. Or get someone to develop it, however sadly we cannot help with sharding as we currently don't have the back-end to support sharding.

**Comment by ncodex2** [comment]
That's okay, but how can i lower my server count to 2500 when i can't even start the bot up?

**Comment by Twentysix26** [comment]
A third party script I assume. I suggest staying up to date with Discord API's news if you want the responsibility of hosting a public bot. Details on sharding have been around since April 2016.
  
Sharding support won't be implemented until the mentioned issues are solved.
