### ISSUE TITLE
how do you wisper embed?

### ISSUE THREAD

**Issue by Artucuno** [Cog-Creators/Red-DiscordBot#760]
how do you whisper embed? 
``` info = em = discord.Embed(color=0x0BFCF2)
        info += em.add_field(name='.', value=(" test"))
        info += await self.bot.say(embed = em)
        await self.bot.wisper(info)```


and im getting this (not sure why)
```
[17/05/2017 17:03] ERROR red on_command_error 369: Exception in command 'help'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/pi/Hexicle/red-discordbot/cogs/testhelp.py", line 18, in help
    info += em.add_field(name='.', value=(" test" ))
TypeError: unsupported operand type(s) for +=: 'Embed' and 'Embed'``` 
can i have help pls? :smile:

**Comment by Kowlin** [comment]
You cannot use ``+=`` in a embed object, since its a object and not a string.

```py
em = discord.Embed(color=0x0BFCF2)
em.add_field(name='.', value=("test"))
await self.bot.say(embed=em)
```

Consider reading the [Discord.py docs](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message) for your trouble. 
For the next time please either use the [Discord API server](https://discord.gg/discord-api) or [our coding channel](https://discord.gg/red). As this repo (and its issue's) are for core Red.
