### ISSUE TITLE
[Red V3] What do you want to see?

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#779]
As the title suggests, what do you want to see out of Red v3, nothing here is off-limits.

**Comment by palmtree5** [comment]
To put this here (though I remember seeing @orels1 mention it in discord): Integrate the redportal cog into downloader (example: this would allow for a one-click install from a search)

**Comment by Stylite** [comment]
Be able to order pizza from the bot and make cleverbot core. I feel bad for coding with this issue

**Comment by pgaetani** [comment]
Will's admin should probably be core.

**Comment by tekulvw** [comment]
Permissions core?

**Comment by palmtree5** [comment]
Both of those

**Comment by orels1** [comment]
@palmtree5 not really like that. I feel like wiring cogs.red into the red itself is not the best idea, due to it being an external service supported by someone from outside of main red dev.

My idea was the following:
>Expose some kind of an API for downloader, so we could call something like `downloader.install_cog(<repo/repoURL>,<cog>)` from inside custom cogs (redportal as an example). So we could, for example have a reaction on `redp search` results embed, that will start installation process without the need to call `cog repo add` and `cog install` manually.

**Comment by pgaetani** [comment]
I like orels' idea... could it even be used for something like cog dependencies? (Yes, I'm going there)

**Comment by SHADOW6** [comment]
Modmail for red:
 https://github.com/Dragory/modmailbot

**Comment by tekulvw** [comment]
Downloader needs to get rewritten then. And I want to see people writing tests for core cogs at the least!

**Comment by Kowlin** [comment]
*"Writing tests"*, its like you want us dead 😂.

**Comment by Eslyium** [comment]
Softban to send an invite link to the user in pms

**Comment by BNegetive** [comment]
to play music from streams on youtube.

**Comment by SHADOW6** [comment]
Suggestion for: Red V3,
+ playlists and Qued music can generate a playlist 
1) song 
2) song
3) song
4) song
5) song
[p]remove # would remove select song from a Que or a list.

+ url.mp3 support
+ Podcast support 
+ if its not bot breaking, how about adding YouTube stream support

Its a rework, so throwing the moon at you. If it can be done Great!
That will mean no one has to worry about it later.

**Comment by AraHaan** [comment]
Red to work with discord.py rewrite branch. v1.0.0

**Comment by tekulvw** [comment]
...everything is now clear

**Comment by boswelja** [comment]
Improved ping command. In my fork, I found a way to put the response time in the message, take a look there :P

**Comment by Jan200101** [comment]
Support for git repos that dont follow a certain format

**Comment by tekulvw** [comment]
@boswelja Negative, the ping command was put into general as s development tool to be able to quickly determine if the bot was responsive with a minimal amount of code getting in the way. This is why the ping command is "hidden" https://github.com/Twentysix26/Red-DiscordBot/blob/develop/cogs/general.py#L47

@Jan200101 No, otherwise we'd have absolutely no way of being able to parse/read repos

**Comment by Redjumpman** [comment]
This is more feature-esque, instead of an implementation detail, but I would like it if Economy allowed bot owners to change the name of their credits. The original modded-economy allowed users to do this, and I applied the same principle to casino. I get msgs all the time like "Hey, I saw that I could change the name of the casino chips to 'Sparky's Love Bucks', can you show me how to do that in economy?" 

If anything, this feature will lower my DM's, which I count as plus. 😝

**Comment by Kowlin** [comment]
I do agree that we require more features to make the bot a bit more personal then other Red bots. The small things like changing the name of the currency will allow us to do that. And let's be fair. It should not be that hard to implement

**Comment by palmtree5** [comment]
That (the economy personalization) is done in https://github.com/Twentysix26/Red-DiscordBot/pull/781/commits/8e79027983a2fa601cf97072160a734f8645d95f

**Comment by AileenLumina** [comment]
I'd love to see if you could take a look at my Dwarf repository and take the ideas you need. I wrote it so every cog can define an API, and it's always predictable how to access a cog's API. Also, I used Django to provide a web interface, which I couldn't finish but I may finish that later this year.

In short: Make coding cogs really straightforward and add a web frontend. You can see my attempt and take whatever code you want from there. Just don't forget to credit if you're going to copypaste some of it. :)

**Comment by EthanC** [comment]
- Look at [RH1N0's Music Bot](https://github.com/Just-Some-Bots/MusicBot) and improve off of that, amazing bot but is beginning to become dated. Specifically, 1 command for all services to play from, as well as force skip for Mods, and a Queue command that shows all queued songs.
- Look at [Brayzure's Mod Bot](https://github.com/Brayzure/utilibot), specifically the Mod Log, and improve however off of that.
- Look at [Kwoth's General Purpose (C#) Bot](https://github.com/Kwoth/NadekoBot) and have a full permission system for commands, such as his.
- Calebj's Punish Cog should be how core Punish works, and should open Cases.
- Warn should open cases as well.
- Softban should PM the user an invite link.
- Red should always work with the latest Discord.py after the rewrite.
- Installing and Updating Cogs isn't very user friendly, I don't think you should have to add an entire repository to install one Cog, thus showing you updates for other Cogs when you go to `!cog update` the one that you have installed.
- Help could use some cleaning up, maybe use the popular reaction-based menu?
- The ability to toggle errors being PMd to the Bot Owner instead of having to open the console.

**Comment by Stylite** [comment]
Rethinkdb as a choice instead of mongo.

**Comment by Jan200101** [comment]
Make the 

> That cog could not be loaded. Check your console or logs for more information.


Error display the error with [p]traceback

**Comment by QingyuChai** [comment]
Right now, prefixes are either the default prefixes or server defined. But what if we allow each user to choose their own prefix? 

Nevermind, bad idea, didn't think it through

**Comment by Kowlin** [comment]
The idea it self isn't bad, but would cause some confusion down the line for regular use. As example, a new user joins a server, and he sees another user use the bot with the prefix ``@@``, the the new user can try and fail due to that little detail.

**Comment by bobloy** [comment]
I could see a per-channel prefix being clearer than per-user, but I'm curious what advantage you see in it? @QingyuChai

**Comment by tekulvw** [comment]
What's the benefit of having per-channel (or user) prefixes when we already have per-server ones? I'm just not seeing it...sure it could be to avoid another bot, but why would you want to avoid it in just one channel?

**Comment by Stylite** [comment]
Make v3 tracebacks print to a gist using pythongists

**Comment by dsvobo** [comment]
Making the bot look cleaner. Making the Help messages an embed would be a very cool feature that some have even made cogs for.

**Comment by tekulvw** [comment]
Last comment from December, I don't think we need this issue open anymore.

**Comment by Sashasonic** [comment]
Embed Whiz (not sure if that's done already.. sometimes it's not long enough - ie: time for each step) or maybe even a link to one like the Nadeko Embed maker / builder uses; but a custom one for Red v3
