### ISSUE TITLE
[p] ignore not working as intended

### ISSUE THREAD

**Issue by gruenf** [Cog-Creators/Red-DiscordBot#791]
I have fiddled around with the bot for a while, but I still have an unresolved issue:
in none of the channel I have tried, the ignore command was working properly (which to me means chmod 0). While writing seems to be blocked, neither reading nor executing was blocked.

You could for example still use economy commands on any ignored channel and they were correctly parsed and executed, there just wasn't a response anymore.

Now the reason this is problematic is that for the main channel it is not possible to prevent anyone, including bots, from reading. This means that internally the bot still processes commands from at least one channel that you actively want it to ignore.

**Comment by calebj** [comment]
Unless you're testing as another user/alt, or asking one to do it for you, this is the correct result.

In the [red.py `user_allowed()` function](https://github.com/Twentysix26/Red-DiscordBot/blob/develop/red.py#L155-L156), the code is such that the bot will never ignore its owner.

**Comment by Twentysix26** [comment]
>**While writing seems to be blocked**, neither reading nor executing was blocked.  

You're overthinking this. All the ignore command does is ignore commands from non privileged users (which means anyone but bot owner and people with mod role and / or admin role).  
Your issue is solvable by setting the [proper permissions](https://support.discordapp.com/hc/en-us/articles/206029707) where applicable and [p]ignore the default channel, since you can't deny "read messages" there.
