### ISSUE TITLE
[Red v3] Help formatter

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#862]
Lets get some opinions on this. Our help formatter is truly ancient. Looking at other bots such as R.Danny and basically every other bot after the embed update on Discord. Should we consider building our own help formatter that is both functional and good looking? As a example we could have a help menu that uses reactions to scroll trough the pages.

Would love to get your opinion on this.

**Comment by Twentysix26** [comment]
Even if it ends up being a new coat of paint instead of a reaction based menu, I'd still be interested in implementing it.  
I've been wanting to look into this for a while, because yeah, despite the embed overuse dislike, they're still way better looking than code blocks 👍

**Comment by SirThane** [comment]
I've been gradually working on a help formatter for my bot (unfortunately on `v1.0.0a`, but easily enough changed with syntactical corrections) that may be exactly what you're talking about. Does exactly what you say, using the logic of the built-in formatter, but send them in embeds instead of code blocks. One of the things I've wanted to do is make it d.py version independent.
![help](https://user-images.githubusercontent.com/15083169/28484219-2eee4002-6e3f-11e7-96fd-33549bf90209.png)
~~(Say what you want about embeds, I see them enough and still like them)~~
EDIT: Sorry it wasn't the reaction controlled pages idea. :\

**Comment by Twentysix26** [comment]
@SirThane That's exactly what I had in mind

**Comment by palmtree5** [comment]
Yep, very much like the idea of making a help system that uses embeds (whether reaction-based menus are involved or not)

**Comment by SirThane** [comment]
https://github.com/SirThane/SESTREN/blob/master/cogs/utils/help.py
Got the rewrite of the cog finished. Unloading will restore the built in formatter without needing to restart. Now works with 0.16.8 and 1.0.0a

**Comment by SirThane** [comment]
Okay, so, aikaterna tested my formatter and brought to my attention two issues that need to be mitigated. First is the fact that my dumb ass didn't implement that paginator that I made for the fields because, in my hubris, I underestimated the amount of commands people may have on their cogs. This is begging for complaints about `HTTPexception 400: BAD REQUEST` because the field value will violate the 1024 character limit. Second is the fact that there is a limit to the number of fields that can be added. Discord silently handles this by simply ignoring any keys in the dict past the 25th. This will be a problem for anyone with 26+ :^) cogs. There are a few ways this can be handled. The built in formatter handled large help manuals by simply paginating into several different messages. This can be done easily enough. Another would be to use the "pages" manual feature, similar to R. Danny. Since we're in this position, we have an opportunity to design it the way we want.

I figured mashing out a reaction based menu would be the preferred option, but I don't like making assumptions. I'll have to move some methods around. Can have it pass a dict back that can be 'paged' over. Use a little logic to determine how long x number of keys will be, and just recreate the embed with a slice of the fields dict. As an improvement to R. Danny's (and I think you can do this), have the bot clear and re-add reactions so that buttons can be clicked again without having to "unclick" by removing your reaction. Maybe add something to the header, or maybe an extra field, for a "Table of Contents" page for [p]help without any args. If so, then a field for instructions on the use of the manual.

**Comment by tekulvw** [comment]
Implemented using a modified version of Thane's help formatter.

**Comment by polyjitter** [comment]
Was a reaction-based paginator ever implemented for the help formatter?

**Comment by flaree** [comment]
> Was a reaction-based paginator ever implemented for the help formatter?

Yes, look under the [p]helpset command.

**Comment by polyjitter** [comment]
Awesome. Thanks!
