### ISSUE TITLE
Payday delay seems bugged

### ISSUE THREAD

**Issue by tardisx** [Cog-Creators/Red-DiscordBot#882]
Cut and pasted from discord:

> [8:32 AM] myusername: !payday
> [8:32 AM] BOTbotusername: @myusername Too soon. For your next payday you have to wait 5 hours, 54 minutes.
>
> (<3 hours later)
>
> [11:08 AM] myusername: !payday
> [11:08 AM] BOTbotusername: @myusername Here, take some credits. Enjoy! (+2400 credits!)

Version info:

>  myusername: !version
> [11:09 AM] BOTbotusername:
> Updates of Red-DiscordBot
> Last three updates
> 10 days ago
> 493a72 - [Trivia] Updated leagueoflegends, leagueults, overwatch lists (#866)
> 10 days ago
> d0768c - [GitHub] Add contributing file (#865)
> 6 weeks ago
> 9f290d - [Mod] No wipe of messages on [p]hackban
> Total commits: 630

**Comment by Eslyium** [comment]
If I recall correctly, If the bot Restarts/Shuts down the timer resets. Did that happen during the time frame?

**Comment by tardisx** [comment]
You know what, you're probably right. That makes sense if the timer isn't persistent across restarts. Sorry for the noise.

**Comment by AeSix** [comment]
Perhaps changing the timer system to store last-check & next-pay times (and
using some math to determine how many pay periods elapsed since last payout
- if wanted) - storing these timestamps would prevent restart resets;
however may cause some per-use latency for very large stores. *shrugs*

Just a thought.

**Comment by Kowlin** [comment]
Possible something for the rewrite, @palmtree5
