### ISSUE TITLE
[Permissions] Main discussion thread

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#903]
Hi everyone, we're going to be adding a rewritten version of Squid-Plugins "permissions" cog to the bot in V3. Please post any ideas/suggestions for improvements or new features regarding permissions here.

**Comment by RSNFreud** [comment]
At the moment locking for everyone but a role doesn't work cross server. You lock for everyone but owner and then allow role but allows everyone to use it on another server.

**Comment by tekulvw** [comment]
Right now global permissions lock is broken iirc.

**Comment by palmtree5** [comment]
tbh there probably should be a `p guild deny` command too (and then make `p channel` have an `allow` subcommand to explicitly allow usage of a command in a specific channel)

Not sure what to do with `p lock` though.

I could envision permissions allowing for "per-guild cogs" (with the owner/co-owners having access to all commands in all cogs globally). Obviously cog loading and unloading has to be done by the owner/co-owners but permissions could be used by guild owners to restrict usage of certain cogs (though a `p guild deny` command should probably be restricted to whatever the equivalent of the `guildowner_or_permissions` check is once #902 has been dealt with).

The way I envision this in terms of perms levels for commands:

`p guild deny` - Guild owner (or probably anyone with the administrator permission)/Bot owners and co-owners

`p channel deny` - Admin role and up?

`p role deny` - Admin role and up?

`p reset` - same as `p guild deny`

**Comment by mikeshardmind** [comment]
Personal thoughts on this:

The further customization of permissions is nice, but if this is going to be a core feature, then there should be checks offered to accommodate them rather than shimming in checks after the fact.

As an example, `red_serverperms_or(**default_required_perms)`

a mapping that could work for storing this would be:

`Cog or command -> scope -> {allowed: [], denied: []}`

Where scope is a snowflake of a guild or channel, and the values for allowed/denied are a list of snowflakes for roles or members. 

Order of precedence would be to take the most specific scope first, and would also prioritize a specific user rule over a role rule should the two conflict in a scope

This would put everything in a check which would leave the defaults up to the cog creator, while allowing server owners/people with admin to modify on a server specific basis.

This should not replace owner/co owner checks, these should replace `admin_or_permission` / `mod_or_permission` The defaults should also only come into consideration if there is not a rule which applies to the user or any of their roles in any relevant scope.

Additionally, this would also remove the need for a mod/admin role to exist in the bot.
