### ISSUE TITLE
[V3] RCON + API implementation

### ISSUE THREAD

**Issue by ScarletRav3n** [Cog-Creators/Red-DiscordBot#990]
As of this moment, there is no way to obtain bot information in a simple manner. Pulling data like the bot's avatar pic, the servers it is in, as well as whether it is online/offline/has no connection are lost causes. The only real things that can be read are anything in the config.

Mainly I want to be able to execute a command outside of my discord client. Press a button or run a script, and the bot does the ping command in a specified server/channel. As an admin, implementations like this make it easier to jump in and do my job.

This can also open the gates to GUI launchers, web access, and even a mobile app.

**Comment by pgaetani** [comment]
An excerpt from my conversation with Will when I was trying to something like this.

> PanKEK please tell me you're not trying to expose command methods

> :ahnf:

> Dude that's gonna be awful
You're gonna have to create context
Danny will murder you

> dammit

>lol yeah it's not simple

>while not simple, I'm seeing it's possible
but very well, I won't incur the wrath of danny

>It's possible but how much stuff is gonna break because of it?
You'd have to create a fake message, author, guild, channel

>could I not get that from the bot somehow?

>And then reimplement dpy internals
But from where?
You're calling a command from outside of discord
You have absolutely zero context

>ok, rather than expose commands then, there has to be some info from the bot I can expose

>Ofc
You can expose all methods that aren't command objects
All you'd have to do is iterate through dir() and expose all callable methods that aren't magical
Or better yet
Instead of exposing each method
Allow someone to pass in the string name of a method
And then attempt to call it yourself

Which then turned into a conversation about exposing stuff from config.
Have not advanced much in that regard due to time; long story short, not 100% sure about what can be exposed yet, but commands (like your ping suggestion) seem like a no-go. Perhaps some hard-coded stuff can be done though, or if cogs are abstracted enough to not have all the logic within command objects, something could be worked out with that as well.

And before you start cussing me out again, just putting this here for perspective and perhaps ideas can sprout from it.

**Comment by tekulvw** [comment]
Working on this in #1017 but it's looking like creating a custom context object (and more specifically a custom message object) is going to be extremely difficult and I am not planning on adding that to the linked PR.

**Comment by tekulvw** [comment]
Initial framework added in #1017 it will allow you to start pulling information (and allows you to add new methods to call over RPC) but it does not have the ability to create custom context objects. It is ridiculously difficult and shouldn't fall under the scope of this issue.
